#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

if [[ -f "${HOME}/.sdkman/bin/sdkman-init.sh" ]]; then
  log 'SDKMAN already installed'
  exit 0
fi

log 'Installing SDKMAN'
if [[ -d "${HOME}/.sdkman" ]]; then
  # chezmoi will have created ~/.sdkman and the SDKMAN install script assumes
  # that the presence of this directory means that SDKMAN has already been
  # installed and will not actually install SDKMAN. This directory should only
  # contain a symlink to ~/.config/sdkman/config. This symlink will be
  # re-created later in this script.
  rm --recursive "${HOME}/.sdkman"
fi
# Retry due to random timeouts
base_sleep_time=30
tries=0
until dl 'https://get.sdkman.io?rcupdate=false' | bash; do
  ((tries += 1))
  if ((tries > 10)); then
    die "Failed to install SDKMAN in 10 tries"
  fi
  rm -rf "${HOME}/.sdkman"
  sleep "$((base_sleep_time * tries))"
done
log 'Installed SDKMAN'

if [[ -f "${HOME}/.config/sdkman/config" ]]; then
  ln --symbolic --force "${HOME}/.config/sdkman/config" "${HOME}/.sdkman/etc/config"
fi
