#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

if [[ ! -f "${HOME}/.sdkman/bin/sdkman-init.sh" ]]; then
  exit 0
fi
if ! prompt_yn 'Install SDKMAN packages?'; then
  exit 0
fi

log 'Installing SDKMAN packages'
cp "${HOME}/.sdkman/etc/config" "${HOME}/.sdkman/etc/config.orig"
sed --in-place 's/sdkman_auto_answer=false/sdkman_auto_answer=true/g' "${HOME}/.sdkman/etc/config"
set +u
# shellcheck disable=SC1091
source "${HOME}/.sdkman/bin/sdkman-init.sh"
readonly sdkman_url='https://raw.githubusercontent.com/rvenutolo/packages/main/sdkman.csv'
dl "${sdkman_url}" | tail --lines='+2' | cut --delimiter=',' --fields='2' | while read -r pkg; do
  log "Installing ${pkg} with SDKMAN"
  base_sleep_time=30
  tries=0
  until
    if [[ "${pkg}" == 'java' ]]; then
      sdk list java | grep --fixed-strings '|' | cut --delimiter='|' --fields='6' | grep '\-tem\s*$' | tac | while read -r jdk; do
        sdk install java "${jdk}"
      done
    else
      sdk install "${pkg}"
    fi
  do
    ((tries += 1))
    if ((tries > 10)); then
      die "Failed to install in 10 tries: ${pkg}"
    fi
    sleep "$((base_sleep_time * tries))"
  done
done
set -u
log 'Installed SDKMAN packages'

mv "${HOME}/.sdkman/etc/config.orig" "${HOME}/.sdkman/etc/config"
