#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

if ! is_arch && ! is_manjaro && ! is_endeavour; then
  exit 0
fi

readonly service_desc='pkgfile database update'
readonly service_unit='pkgfile-update.timer'
readonly required_executable='pkgfile'
readonly system_or_user='system'

enable_service "${service_desc}" "${service_unit}" "${required_executable}" "${system_or_user}"
