#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if executable_exists 'reflector'; then
  enable_system_service_unit 'reflector.timer'
fi
