#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

if ! is_arch && ! is_endeavour; then
  exit 0
fi

readonly service_desc='Reflector'
readonly service_unit='reflector.service'

enable_system_service "${service_desc}" "${service_unit}"
