#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

if ! executable_exists 'reflector'; then
  if is_arch; then
    log 'reflector executable not found'
  fi
  exit 0
fi

readonly target_file="${HOME}/.etc/reflector.conf"
readonly link_file='/etc/xdg/reflector/reflector.conf'
link_system_file "${target_file}" "${link_file}"
