#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

if ! is_arch && ! is_endeavour; then
  exit 0
fi

if ! executable_exists 'reflector'; then
  log 'reflector executable not found'
  exit 0
fi

readonly target_file="${HOME}/.etc/reflector.conf"
readonly link_file='/etc/xdg/reflector/reflector.conf'
link_system_file "${target_file}" "${link_file}"
