#!/usr/bin/env bash

# @description Add the Chaotic AUR keyring and mirror list to pacman on Arch/CachyOS hosts.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

if ! os::is_arch && ! os::is_cachyos; then
  exit 0
fi
if ! commands::executable_exists 'pacman'; then
  log::log 'pacman executable not found'
  exit 0
fi

if pacman-key --list-keys | grep::contains_exactly_ignore_case 'FBA220DFC880C036'; then
  exit 0
fi
if ! prompt::yn 'Add Chaotic AUR keyring and mirror list?'; then
  exit 0
fi

log::log 'Adding Chaotic AUR keyring and mirror list'
sudo pacman-key --recv-key 'FBA220DFC880C036' --keyserver 'keyserver.ubuntu.com'
sudo pacman-key --lsign-key 'FBA220DFC880C036'
sudo pacman --upgrade --noconfirm \
  'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' \
  'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
log::log 'Added Chaotic AUR keyring and mirror list'
log::log 'Refreshing pacman package database'
sudo pacman --sync --refresh
log::log 'Refreshed pacman package database'
