#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if is_server; then
  exit 0
fi

if ! executable_exists 'gnome-session'; then
  exit 0
fi

enable_user_service_unit 'gnome-remote-desktop.service'
