#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! commands::executable_exists 'flatpak'; then
  exit 0
fi

if files::exists '/var/lib/flatpak/repo/config'; then
  exit 0
fi

dirs::root_create '/var/lib/flatpak/repo/objects' '/var/lib/flatpak/repo/tmp'
files::root_write '/var/lib/flatpak/repo/config' '[core]
repo_version=1
mode=bare-user-only
min-free-space-size=500MB'
