#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! executable_exists 'flatpak'; then
  exit 0
fi

if file_exists '/var/lib/flatpak/repo/config'; then
  exit 0
fi

root_create_dir '/var/lib/flatpak/repo/objects' '/var/lib/flatpak/repo/tmp'
root_write_file '/var/lib/flatpak/repo/config' '[core]
repo_version=1
mode=bare-user-only
min-free-space-size=500MB'
