#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

if ! executable_exists 'tailscale'; then
  exit 0
fi

if ! tailscale status > /dev/null && prompt_yn 'Connect to Tailscale network?'; then
  sudo tailscale up
  log "Tailscale IP: $(tailscale ip -4)"
fi
