#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if timedatectl show | grep::contains_exactly 'NTP=yes'; then
  exit 0
fi
if ! prompt::yn 'Set timedatectl NTP on?'; then
  exit 0
fi

log::log 'Setting time NTP on'
sudo timedatectl set-ntp on
log::log 'Set time NTP on'
