#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_at_most_1_arg "$@"

if [[ "$#" -eq 0 ]]; then
  readonly tz='America/New_York'
else
  readonly tz="$1"
fi

if timedatectl show | contains_regex "^Timezone=${tz}$"; then
  exit 0
fi
if ! prompt_yn "Set timezone to: ${tz}"; then
  exit 0
fi

log "Setting timezone to: ${tz}"
sudo timedatectl set-timezone "${tz}"
log "Set timezone to: ${tz}"
