#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if timedatectl show | contains_exactly 'NTP=yes'; then
  exit 0
fi
if ! prompt_yn 'Set timedatectl NTP on?'; then
  exit 0
fi

log 'Setting time NTP on'
sudo timedatectl set-ntp on
log 'Set time NTP on'
