#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_at_most_1_arg "$@"

if [[ "$#" -eq 0 ]]; then
  if is_server; then
    tz='Etc/UTC'
  else
    tz='America/New_York'
  fi
else
  tz="$1"
fi
readonly tz

if timedatectl show | grep --quiet "^Timezone=${tz}$"; then
  exit 0
fi
if ! prompt_yn "Set timezone to: ${tz}"; then
  exit 0
fi

log "Setting timezone to: ${tz}"
sudo timedatectl set-timezone "${tz}"
log "Set timezone to: ${tz}"
