#!/usr/bin/env bash

# @description Interactively enable NTP time synchronization via timedatectl when not already on.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

if timedatectl show | grep::contains_exactly 'NTP=yes'; then
  exit 0
fi
if ! prompt::yn 'Set timedatectl NTP on?'; then
  exit 0
fi

log::log 'Setting time NTP on'
sudo timedatectl set-ntp on
log::log 'Set time NTP on'
