ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - .claude/**
functions:
  - changed-files:
      - any-glob-to-any-file:
          - scripts/functions/**
install:
  - changed-files:
      - any-glob-to-any-file:
          - scripts/install/**
scripts:
  - changed-files:
      - any-glob-to-any-file:
          - scripts/non-interactive/**
          - scripts/interactive/**
          - scripts/shims/**
misc:
  - changed-files:
      - any-glob-to-any-file:
          - scripts/misc/**
other:
  - changed-files:
      - any-glob-to-any-file:
          - scripts/other/**
set_up:
  - changed-files:
      - any-glob-to-any-file:
          - scripts/set_up/**
test:
  - changed-files:
      - any-glob-to-any-file:
          - test/**
