#!/usr/bin/env bash

# @description Install the stable Rust toolchain via rustup when rustup is present and stable isn't already installed.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

if ! commands::executable_exists 'rustup'; then
  exit 0
fi
if [[ "$(rustup toolchain list)" == 'stable'* ]]; then
  exit 0
fi
if ! prompt::yn 'Set rustup toolchain to stable?'; then
  exit 0
fi

log::log 'Setting rustup toolchain to stable'
rustup toolchain install 'stable'
log::log 'Set rustup toolchain to stable'
