#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
require_bash_version 4 3

assert_paths_exist "$@"

mapfile -t candidates < <(find_shell_scripts "$@")
if [[ "${#candidates[@]}" -eq 0 ]]; then
  exit 0
fi

files=()
filter_shell_scripts files "${candidates[@]}"
if [[ "${#files[@]}" -eq 0 ]]; then
  exit 0
fi

rc=0
shfmt --list --indent=2 --case-indent --binary-next-line --space-redirects --diff "${files[@]}" || rc=1
shellcheck "${files[@]}" || rc=1
exit "${rc}"
