#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"
check_not_root

shfmt --find "$(this_script_dir)" \
  | grep --invert-match '/other/' \
  | xargs shfmt --list --indent '2' --case-indent --binary-next-line --space-redirects --write
