#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

shfmt --find "${SCRIPTS_DIR}" \
  | grep --invert-match '/other/' \
  | xargs shfmt --list --indent '2' --case-indent --binary-next-line --space-redirects --write
