site_name: rvenutolo/scripts
site_url: https://rvenutolo.github.io/scripts/
repo_url: https://github.com/rvenutolo/scripts
repo_name: rvenutolo/scripts
docs_dir: docs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
nav:
  - Home: index.md
  - Functions: functions/index.md
  - Scripts: scripts/index.md
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
