#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/lib/functions.bash"
check_no_args "$@"

shfmt \
  --list \
  --indent 2 \
  --case-indent \
  --binary-next-line \
  --space-redirects \
  --write \
  "$(this_script_dir)/lib" "$(this_script_dir)/main" "$(this_script_dir)/setup"
