#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/lib/functions.bash"
check_no_args "$@"
check_not_root

sudo --validate

if [[ -f "${HOME}/.profile" ]]; then
  # shellcheck disable=SC1091
  source "${HOME}/.profile"
fi

readonly install_scripts_dir="${SCRIPTS_DIR}/install"
LC_COLLATE='C'
for script in "${install_scripts_dir}"/*; do
  # don't attempt to execute any READMEs or scripts that intentionally have their executability turned off
  if [[ -x "${script}" ]]; then
    log "Running: ${script#"${install_scripts_dir}"/}"
    "$script"
    log "Ran: ${script#"${install_scripts_dir}"/}"
  fi
done
