#!/usr/bin/env bash

set -euo pipefail

if [[ -f "${HOME}/.profile" ]]; then
  # shellcheck disable=SC1091
  source "${HOME}/.profile"
fi

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

sudo --validate

readonly scripts_dir="${SCRIPTS_DIR}/set_up"
LC_COLLATE='C'
for script in "${scripts_dir}"/**/*; do
  # don't attempt to execute any READMEs or scripts that intentionally have their executability turned off
  if [[ -x "${script}" ]]; then
    log "Running: ${script#"${scripts_dir}"/}"
    "$script"
    log "Ran: ${script#"${scripts_dir}"/}"
  fi
done
