#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

if [[ -f "${HOME}/.profile" ]]; then
  # shellcheck disable=SC1091
  source "${HOME}/.profile"
fi

#shellcheck disable=SC1091,SC2153
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::check_no_args "$@"

sudo --validate

readonly scripts_dir="${SCRIPTS_DIR}/set_up"
export LC_COLLATE='C'
shopt -s globstar
for script in "${scripts_dir}"/**/*; do
  # don't attempt to execute directories, READMEs, or scripts that intentionally have their executability turned off
  if files::is_executable "${script}"; then
    log::log "Running: ${script#"${scripts_dir}"/}"
    "${script}"
    log::log "Ran: ${script#"${scripts_dir}"/}"
  fi
done
