#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"
check_not_root

sudo --validate

if [[ -f "${HOME}/.profile" ]]; then
  # shellcheck disable=SC1091
  source "${HOME}/.profile"
fi

readonly setup_scripts_dir="${SCRIPTS_DIR}/setup"
LC_COLLATE='C'
for script in "${setup_scripts_dir}"/**/*; do
  # don't attempt to execute any READMEs or scripts that intentionally have their executability turned off
  if [[ -x "${script}" ]]; then
    log "Running: ${script#"${setup_scripts_dir}"/}"
    "$script"
    log "Ran: ${script#"${setup_scripts_dir}"/}"
  fi
done
