#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 3

shell_scripts::assert_paths_exist "$@"

files::create_temp candidates_tmp
# shellcheck disable=SC2154 # candidates_tmp set via nameref inside files::create_temp
shell_scripts::find "$@" > "${candidates_tmp}"
mapfile -t candidates < "${candidates_tmp}"
if [[ "${#candidates[@]}" -eq 0 ]]; then
  exit 0
fi

files=()
shell_scripts::filter files "${candidates[@]}"
if [[ "${#files[@]}" -eq 0 ]]; then
  exit 0
fi

shellcheck "${files[@]}"
