#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_most_1_arg "$@"

if strings::is_not_empty "${1:-}"; then
  readonly profile="$1"
else
  readonly profile='de-core-dev'
fi

aws sso login --sso-session 'de' --profile "${profile}"
aws --profile "${profile}" sts get-caller-identity
printf '%s\n' "run: export AWS_PROFILE='${profile}'"
