#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_at_least_1_arg "$@"

filetime="$(date +%Y%m%d_%H%M%S)"
readonly filetime
for file; do
  if [[ -f "${file}" || -d "${file}" ]]; then
    dirname="$(dirname -- "${file}")"
    filename="$(basename -- "${file}")"
    target_file="${dirname}/${filename}.${filetime}.bak"
    cp --archive -- "${file}" "${target_file}"
    log "${file} -> ${target_file}"
  else
    die "${file} is not a regular file or directory"
  fi
done
