#!/usr/bin/env bash

# @description Create a timestamped backup copy of each given file or directory.
# @arg $@ paths One or more file or directory paths to back up.
# @exitcode 0 All files/directories backed up successfully.
# @exitcode 1 A path does not exist as a file or directory.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_at_least_1_arg "$@"

filetime="$(date +%Y%m%d_%H%M%S)"
readonly filetime
for file in "$@"; do
  if files::exists "${file}" || dirs::exists "${file}"; then
    dirname="$(dirname -- "${file}")"
    filename="$(basename -- "${file}")"
    target_file="${dirname}/${filename}.${filetime}.bak"
    cp --archive -- "${file}" "${target_file}"
    log::log "${file} -> ${target_file}"
  else
    log::die "${file} is not a regular file or directory"
  fi
done
