#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_least_1_arg "$@"

filetime="$(date +%Y%m%d_%H%M%S)"
readonly filetime
for file in "$@"; do
  if files::exists "${file}" || dirs::exists "${file}"; then
    dirname="$(dirname -- "${file}")"
    filename="$(basename -- "${file}")"
    target_file="${dirname}/${filename}.${filetime}.bak"
    cp --archive -- "${file}" "${target_file}"
    log::log "${file} -> ${target_file}"
  else
    log::die "${file} is not a regular file or directory"
  fi
done
