#!/usr/bin/env bash

# @description Run batfetch (a system info / fastfetch-style tool) via `nix run`.
# @arg $@ args Optional arguments forwarded verbatim to batfetch.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
# pass-through: any arg count valid (forwarded to batfetch)

nix run 'github:ashish-kus/batfetch' -- "$@"
