#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

if args::stdin_exists; then
  args::check_exactly_1_arg "$@"
  awk --field-separator "$1" 'NR==1{nf=NF} NF!=nf{print "Line " NR " has " NF " fields (expected " nf "): " $0}'
else
  awk --field-separator "$2" 'NR==1{nf=NF} NF!=nf{print "Line " NR " has " NF " fields (expected " nf "): " $0}' "$1"
fi
