#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_most_1_arg "$@"

if [[ "$#" -eq 0 ]]; then
  readonly hostname='google.com'
else
  readonly hostname="$1"
fi

docker run --rm alpine nslookup "${hostname}"
