#!/usr/bin/env bash

# @description Verify Docker container DNS resolution by running nslookup inside an alpine container.
# @arg $1 hostname Optional hostname to resolve (defaults to 'google.com').

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_at_most_1_arg "$@"

if args::no_args "$@"; then
  readonly hostname='google.com'
else
  readonly hostname="$1"
fi

docker run --rm alpine nslookup "${hostname}"
