#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_at_most_1_arg "$@"

if [[ "$#" -eq 0 ]]; then
  readonly hostname='google.com'
else
  readonly hostname="$1"
fi

docker run --rm alpine nslookup "${hostname}"
