#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# elsewhere in the script needs sudo, so prompt for password before rest of script runs
sudo --validate

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if strings::is_empty "$(w --no-header "${USER}")"; then
  log::die "${USER} is not logged in"
fi

readonly expected_locale='LANG=en_US.UTF-8'
if ! localectl | grep::contains_exactly "${expected_locale}"; then
  log::log "Locale is not: ${expected_locale}"
fi

if ! timedatectl show | grep::contains_exactly 'NTP=yes'; then
  log::log "timedatectl NTP is not on"
fi

readonly expected_tz='America/New_York'
if ! timedatectl show | grep::contains_regex "^Timezone=${expected_tz}$"; then
  log::log "Timezone is NOT ${expected_tz}"
fi

if ! loginctl show-user "${USER}" --property=Linger 2> '/dev/null' | grep::contains_word_ignore_case 'yes'; then
  log::log "${USER} is not set to linger"
fi

user_groups="$(groups "${USER}")"
readonly user_groups
all_groups="$(getent group | cut --delimiter=':' --fields=1)"
readonly all_groups
readonly groups=('adm' 'admin' 'docker' 'kvm' 'input' 'libvirt' 'libvirtd' 'sudo' 'sys' 'wheel')
for group in "${groups[@]}"; do
  if ! grep::contains_word "${group}" <<< "${all_groups}"; then
    continue
  fi
  if grep::contains_word "${group}" <<< "${user_groups}"; then
    continue
  fi
  log::log "User is not in group: ${group}"
done

readonly expected_vars=(
  'EDITOR'
  'MANPAGER'
  'PAGER'
  'XDG_CACHE_HOME'
  'XDG_CONFIG_HOME'
  'XDG_DATA_HOME'
  'XDG_STATE_HOME'
  'XDG_DATA_DIRS'
  'SCRIPTS_DIR'
  'CODE_DIR'
  'SDKMAN_DIR'
)
for var in "${expected_vars[@]}"; do
  if strings::is_empty "${!var:-}"; then
    log::log "Environment variable not set: ${var}"
  fi
done

# set these if not set
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}/.config"}"
SDKMAN_DIR="${SDKMAN_DIR:-"${HOME}/.sdkman"}"
CODE_DIR="${CODE_DIR:-"${HOME}/Code"}"
SCRIPTS_DIR="${SCRIPTS_DIR:-"${CODE_DIR}/Personal/scripts"}"

## remove from path so scripts that mask commands are no longer on PATH, ex: mvn
path::remove "${SCRIPTS_DIR}/main"
path::remove "${SCRIPTS_DIR}/other"

if commands::executable_exists 'flatpak' && ! flatpak --user remotes | grep::contains_word_ignore_case 'flathub'; then
  log::log 'Flathub Flatpak repo is not installed'
fi

## check that the `trash` command is from trash-cli and not trash-d
if commands::executable_exists 'trash' \
  && ! trash --help | grep::contains_word_ignore_case 'https://github.com/andreafrancia/trash-cli/issues'; then
  log::log "trash command is not from trash-cli"
fi

## check that the `tldr` command is from tealdeer
if commands::executable_exists 'tldr' && ! tldr --version | grep::contains_word_ignore_case 'tealdeer'; then
  log::log "tldr command is not from tealdeer"
fi

if commands::executable_exists 'ufw'; then
  ufw_status="$(sudo ufw status verbose)"
  readonly ufw_status
  if ! grep::contains_word_ignore_case 'status: active' <<< "${ufw_status}"; then
    log::log "UFW is not active"
  fi
  if ! grep::contains_word_ignore_case 'deny (incoming)' <<< "${ufw_status}"; then
    log::log "UFW is not denying incoming by default"
  fi
  if ! grep::contains_word_ignore_case 'allow (outgoing)' <<< "${ufw_status}"; then
    log::log "UFW is not allowing outgoing by default"
  fi
fi

if commands::executable_exists 'aa-enabled' && ! aa-enabled | grep::contains_word_ignore_case 'yes'; then
  log::log "AppArmor is not enabled"
fi

if commands::executable_exists 'sestatus' \
  && sestatus | grep::contains_perl_regex_ignore_case 'selinux status:\s+enabled'; then
  log::log "SELinux is enabled"
fi

expected_files=(
  "${HOME}/.bash_profile"
  "${HOME}/.bashrc"
  "${HOME}/.profile"
  "${XDG_CONFIG_HOME}/bash/local.bash"
  "${HOME}/.ssh/config.private"
  "${SDKMAN_DIR}/bin/sdkman-init.sh"
  '/etc/fail2ban/jail.local'
  '/etc/ssh/sshd_config.d/sshd.conf'
  '/etc/sudoers.d/disable-admin-flag'
  '/etc/sudoers.d/timestamp-timeout'
)
if hosts::is_personal; then
  expected_files+=(
    '/etc/sysctl.d/kvals.conf'
    '/etc/sysctl.d/max-user-watches.conf'
  )
fi
readonly expected_files
for file in "${expected_files[@]}"; do
  if ! files::exists "${file}"; then
    log::log "Missing file: ${file}"
  fi
  if ! files::is_readable "${file}"; then
    log::log "Cannot read file: ${file}"
  fi
done

readonly unwanted_files=(
  "${HOME}/.bash_login"
  "${HOME}/.bash_logout"
  "${HOME}/.bash_history"
  "${HOME}/.lesshst"
)
for file in "${unwanted_files[@]}"; do
  if files::exists "${file}"; then
    log::log "Unwanted file: ${file}"
  fi
done

if ! hosts::is_server; then
  readonly expected_fonts=(
    'Code New Roman'
    'Fantasque Sans Mono'
    'Fira Code'
    'FreeMono'
    'Hack'
    'Hasklig'
    'Inconsolata'
    'Input'
    'Iosevka'
    'JetBrains Mono'
    'JoyPixels'
    'Menlo'
    'Monoid'
    'Mononoki'
    'Noto Color Emoji'
    'Roboto Mono'
    'Source Code Pro'
    'Terminess'
    'Ubuntu Mono'
  )

  if commands::executable_exists 'fc-list'; then
    installed_fonts="$(fc-list : family)"
    readonly installed_fonts
    for font in "${expected_fonts[@]}"; do
      font_no_space="${font//[[:space:]]/}"
      if ! grep::contains_word_ignore_case "${font}" <<< "${installed_fonts}" \
        && ! grep::contains_word_ignore_case "${font}TTF" <<< "${installed_fonts}" \
        && ! grep::contains_word_ignore_case "${font_no_space}" <<< "${installed_fonts}" \
        && ! grep::contains_word_ignore_case "${font_no_space}TTF" <<< "${installed_fonts}"; then
        log::log "Font not available: ${font}"
      fi
    done
  else
    log::log 'No fc-list, skipping font checks'
  fi
fi

expected_active_system_services=(
  'fail2ban.service'
  'ufw.service'
)
if ! hosts::is_server; then
  expected_active_system_services+=('cups.service')
fi
if commands::executable_exists 'aa-enabled'; then
  expected_active_system_services+=('apparmor.service')
fi
if commands::executable_exists 'CrashPlanDesktop'; then
  expected_active_system_services+=('crashplan-pro.service')
fi
if commands::executable_exists 'containerd'; then
  expected_active_system_services+=('containerd.service')
fi
if commands::executable_exists 'pkgfile'; then
  expected_active_system_services+=('pkgfile-update.timer')
fi
if commands::executable_exists 'reflector'; then
  expected_active_system_services+=('reflector.timer')
fi
if commands::executable_exists 'tailscaled'; then
  expected_active_system_services+=('tailscaled.service')
fi
readonly expected_active_system_services
for service in "${expected_active_system_services[@]}"; do
  if ! systemctl is-active --quiet "${service}"; then
    log::log "System service not active: ${service}"
  fi
done

expected_enabled_system_services=(
  'sshd.service'
)
if commands::executable_exists 'libvirtd'; then
  expected_enabled_system_services+=('libvirtd.service')
fi
readonly expected_enabled_system_services
for service in "${expected_enabled_system_services[@]}"; do
  if ! systemctl::is_system_unit_enabled "${service}"; then
    log::log "System service not enabled: ${service}"
  fi
done

expected_active_user_services=(
  'journalctl-vacuum.timer'
  'ssh-agent.service'
  'trash-cleanup.timer'
  'trash-empty.timer'
)
if commands::executable_exists 'dockerd'; then
  expected_active_user_services+=('docker.service')
fi
readonly expected_active_user_services
for service in "${expected_active_user_services[@]}"; do
  if ! systemctl is-active --user --quiet "${service}"; then
    log::log "User service not active: ${service}"
  fi
done

readonly expected_enabled_user_services=()
for service in "${expected_enabled_user_services[@]}"; do
  if ! systemctl::is_user_unit_enabled "${service}"; then
    log::log "User service not enabled: ${service}"
  fi
done

if ! hosts::is_server; then
  readonly expected_kvals=(
    'vm.dirty_background_ratio 5'
    'vm.dirty_ratio 5'
    'vm.max_map_count 2147483642'
    'vm.swappiness 10'
  )
  for kvals in "${expected_kvals[@]}"; do
    IFS=' ' read -r k v <<< "${kvals}"
    if [[ ! $(sysctl --values "${k}") -le "${v}" ]]; then
      log::log "Kernel variable ${k} is >${v}: $(sysctl --values "${k}")"
    fi
  done
fi

if commands::executable_exists 'pacman'; then
  pacman_conf_text="$(< '/etc/pacman.conf')"
  readonly pacman_conf_text
  for pacman_repo in 'multilib' 'chaotic-aur'; do
    if ! grep::contains_exactly "[${pacman_repo}]" <<< "${pacman_conf_text}"; then
      log::log "Pacman ${pacman_repo} repo is missing"
    fi
  done
fi

if os::is_fedora; then
  readonly expected_dnf_conf_vals=('max_parallel_downloads' 'defaultyes' 'keepcache')
  dnf_conf_text="$(< '/etc/dnf/dnf.conf')"
  readonly dnf_conf_text
  for dnf_conf_val in "${expected_dnf_conf_vals[@]}"; do
    if strings::is_empty "$(
      strings::trim "$(
        grep --fixed-strings "${dnf_conf_val}" <<< "${dnf_conf_text}" \
          | cut --delimiter='=' --fields=2
      )"
    )"; then
      log::log "dnf conf ${dnf_conf_val} is not set"
    fi
  done
  installed_packages="$(dnf list --installed | cut --delimiter=' ' --fields=1)"
  readonly installed_packages
  readonly expected_rpm_fusions_packages=(
    'rpmfusion-free-appstream-data'
    'rpmfusion-free-release'
    'rpmfusion-nonfree-appstream-data'
    'rpmfusion-nonfree-release'
  )
  for rpm_fusion_pacakge in "${expected_rpm_fusions_packages[@]}"; do
    if ! grep::contains_word "${rpm_fusion_pacakge}" <<< "${installed_packages}"; then
      log::log "${rpm_fusion_pacakge} is not installed"
    fi
  done
fi
