#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"

# remove this dir from the path so executing `claude` doesn't run the `claude` script
path_remove "$(this_script_dir)"

CLAUDE_CONFIG_DIR="${XDG_CONFIG_HOME}/claude/personal" exec claude '/color green' "$@"
