#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_at_least_1_arg "$@"

readonly file="$1"
shift
case "${file}" in
  *.tar | *.tar.* | *.tbz2 | *.tgz) tar --create --verbose --auto-compress --file "${file}" "$@" ;;
  *.bz2) bzip2 --verbose "${file}" "$@" ;;
  *.gz) gzip --verbose "${file}" "$@" ;;
  *.lzma) xz --verbose --format=lzma "${file}" "$@" ;;
  *.rar) rar a "${file}" "$@" ;;
  *.xz) xz --verbose "${file}" "$@" ;;
  *.zip) zip --verbose "${file}" "$@" ;;
  *.7z) 7z a "${file}" "$@" ;;
  *) die "Filetype not recognized: ${file}" ;;
esac
log "compressed '${file}'"
