#!/usr/bin/env bash

# @description Compress one or more files/directories into an archive, dispatching by the output filename extension.
# @arg $1 file Output archive path; extension selects the compressor (.tar*, .bz2, .gz, .lzma, .rar, .xz, .zip, .7z).
# @arg $@ inputs Files/directories to add to the archive.
# @exitcode 1 Output filename has an unrecognized extension.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_least_1_arg "$@"

readonly file="$1"
shift
case "${file}" in
  *.tar | *.tar.* | *.tbz2 | *.tgz) tar --create --verbose --auto-compress --file "${file}" "$@" ;;
  *.bz2) bzip2 --verbose "${file}" "$@" ;;
  *.gz) gzip --verbose "${file}" "$@" ;;
  *.lzma) xz --verbose --format=lzma "${file}" "$@" ;;
  *.rar) rar a "${file}" "$@" ;;
  *.xz) xz --verbose "${file}" "$@" ;;
  *.zip) zip --verbose "${file}" "$@" ;;
  *.7z) 7z a "${file}" "$@" ;;
  *) log::die "Filetype not recognized: ${file}" ;;
esac
log::log "compressed '${file}'"
