#!/usr/bin/env bash

# @description Print journalctl entries mentioning core dumps.
# @noargs
# @stdout Matching journalctl lines.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is not statically followable
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

journalctl | grep --fixed-strings 'dumped core'
