#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_exactly_2_args "$@"

# Copy file with a progress bar
strace --quiet -ewrite cp -- "$1" "$2" 2>&1 | awk '{
  count += $NF
  if (count % 10 == 0) {
    percent = count / total_size * 100
    printf "%3d%% [", percent
    for (i=0;i<=percent;i++)
      printf "="
      printf ">"
      for (i=percent;i<100;i++)
        printf " "
        printf "]\r"
  }
}
END { print "" }' total_size="$(stat --format='%s' "$1")" count=0
