#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_exactly_2_args "$@"
readonly SRC="$1"
readonly DEST="$2"

# Copy file with a progress bar
strace --quiet -ewrite cp -- "${SRC}" "${DEST}" 2>&1 | awk '{
  count += $NF
  if (count % 10 == 0) {
    percent = count / total_size * 100
    printf "%3d%% [", percent
    for (i=0;i<=percent;i++)
      printf "="
      printf ">"
      for (i=percent;i<100;i++)
        printf " "
        printf "]\r"
  }
}
END { print "" }' total_size="$(stat --format='%s' "${SRC}")" count=0
