#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_least_1_arg "$@"

for file in "$@"; do
  if files::exists "${file}"; then
    target_file="${CRYPT_DIR}/$(basename -- "${file}")"
    log::log "Encrypting: ${file} to: ${target_file}"
    age --encrypt --recipient="${AGE_PUBLIC_KEY}" --armor --output="${target_file}" -- "${file}"
  else
    log::die "${file} is not file"
  fi
done
