#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/../lib/functions.sh"
check_exactly_1_arg "$@"

mimeType=$(file -b --mime-type "$1")
if [[ $mimeType == text/* ]]; then
  mimeType="${mimeType};charset=utf-8"
fi
readonly mimeType
echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr --delete '\n')"
