#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_exactly_1_arg "$@"

MIME_TYPE="$(file --brief --mime-type "$1")"
if [[ "${MIME_TYPE}" == text/* ]]; then
  MIME_TYPE="${MIME_TYPE};charset=utf-8"
fi
readonly MIME_TYPE
printf '%s\n' "data:${MIME_TYPE};base64,$(openssl base64 -in "$1" | tr --delete '\n')"
