#!/usr/bin/env bash

# @description Print a base64-encoded `data:` URL for the given file, inferring the MIME type with `file`.
# @arg $1 input_file Path to the file to encode.
# @stdout The data URL on a single line.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_exactly_1_arg "$@"
readonly INPUT_FILE="$1"

MIME_TYPE="$(file --brief --mime-type "${INPUT_FILE}")"
if [[ "${MIME_TYPE}" == text/* ]]; then
  MIME_TYPE="${MIME_TYPE};charset=utf-8"
fi
readonly MIME_TYPE
printf '%s\n' "data:${MIME_TYPE};base64,$(openssl base64 -in "${INPUT_FILE}" | tr --delete '\n')"
