#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_exactly_2_args "$@"

if ! file_exists "$1"; then
  die "File does not exist: $1"
fi

if ! file_exists "$2"; then
  die "File does not exist: $2"
fi

diff --color=always --report-identical-files --unified --text \
  <(jq --sort-keys . "$1") \
  <(jq --sort-keys . "$2") \
  | skip_first_lines 3
