#!/usr/bin/env bash

# @description Diff two YAML files semantically by recursively sorting keys with yq first, then producing a colored unified diff.
# @arg $1 file_a Path to the first YAML file.
# @arg $2 file_b Path to the second YAML file.
# @stdout Colored unified diff (or an "identical" line) with the diff header trimmed off.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is not statically followable
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
commands::assert_executable_exists 'yq'
args::check_exactly_2_args "$@"
readonly FILE_A="$1"
readonly FILE_B="$2"

files::assert_exists "${FILE_A}"
files::assert_exists "${FILE_B}"

files::create_temp sorted_a_file
files::create_temp sorted_b_file
# shellcheck disable=SC2154 # sorted_a_file assigned by files::create_temp via nameref
yq --prettyPrint 'sort_keys(..)' "${FILE_A}" > "${sorted_a_file}"
# shellcheck disable=SC2154 # sorted_b_file assigned by files::create_temp via nameref
yq --prettyPrint 'sort_keys(..)' "${FILE_B}" > "${sorted_b_file}"
diff --color=always --report-identical-files --unified --text \
  "${sorted_a_file}" \
  "${sorted_b_file}" \
  | text::skip_first_lines 3
