#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_at_least_1_arg "$@"
check_at_most_2_args "$@"

if [[ -n "${2:-}" ]]; then
  dl "$1" | age --decrypt --identity "${AGE_PRIVATE_KEY_FILE}" --output "$2"
else
  dl "$1" | age --decrypt --identity "${AGE_PRIVATE_KEY_FILE}"
fi
