#!/usr/bin/env bash

# @description Restart the current directory's docker compose project by bringing it down (removing orphans) and back up detached.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

docker compose down --remove-orphans
docker compose up --detach
