#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"

# remove this dir from the path so executing `docker` doesn't execute this script
path_remove "$(this_script_dir)"

if executable_exists 'podman'; then
  podman "$@"
else
  docker "$@"
fi
