#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

readonly ignore_filename='.dc_ignore'

# $1 = compose file
function run_command() {
  docker compose --file "$1" down --remove-orphans
}

if file_exists 'compose.yaml'; then
  run_command './compose.yaml'
else
  find . -name 'compose.yaml' | sort | while read -r compose_file; do
    compose_dir_path="$(dirname "${compose_file}")"
    compose_dir_name="$(basename "${compose_dir_path}")" || exit 1
    if ! file_exists "${compose_dir_path}/${ignore_filename}"; then
      log "Running docker compose down for: ${compose_dir_name}"
      run_command "${compose_file}"
    fi
  done
fi
