#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_no_args "$@"

containers="$(docker ps --filter=status=exited --filter=status=created --quiet)"
readonly containers
if [[ -n "${containers}" ]]; then
  docker rm "${containers}"
fi
