#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.sh"
check_no_args "$@"

readonly containers="$(docker ps --filter=status=exited --filter=status=created --quiet)"
if [[ -n "${containers}" ]]; then
  docker rm "${containers}"
fi
