#!/usr/bin/env bash

# @description Run aquasec/trivy against the given Docker images (or all running container images when no args).
# @arg $@ images Optional list of image references to scan; defaults to images of currently running containers.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash sourced from DOCKER_COMPOSE_DIR at runtime
source "${DOCKER_COMPOSE_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

if args::no_args "$@"; then
  files::create_temp images_tmp
  # shellcheck disable=SC2154 # images_tmp assigned by files::create_temp nameref
  docker ps --format '{{.Image}}' | sort | uniq > "${images_tmp}"
  mapfile -t images_to_scan < "${images_tmp}"
else
  images_to_scan=("$@")
fi
readonly images_to_scan

readonly tmp_cache_dir='/tmp/trivy/cache'
dirs::create "${tmp_cache_dir}"

for image in "${images_to_scan[@]}"; do
  log::log "Scanning: ${image}"
  docker run \
    --rm \
    --volume "${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock" \
    --volume "${tmp_cache_dir}:/root/.cache" \
    --name "trivy-${image//[:\/]/-}" \
    'aquasec/trivy:latest' \
    '--quiet' \
    'image' \
    "${image}"
  log::log "Scanned: ${image}"
done
