#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash sourced from DOCKER_COMPOSE_DIR at runtime
source "${DOCKER_COMPOSE_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

if [[ "$#" -eq 0 ]]; then
  mapfile -t images_to_scan < <(docker ps --format '{{.Image}}' | sort | uniq)
else
  images_to_scan=("$@")
fi
readonly images_to_scan

readonly tmp_cache_dir='/tmp/grype/cache'
dirs::create "${tmp_cache_dir}"

for image in "${images_to_scan[@]}"; do
  log::log "Scanning: ${image}"
  docker run \
    --rm \
    --volume "${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock" \
    --volume "${tmp_cache_dir}:/.cache/grype" \
    --name "grype-${image//[:\/]/-}" \
    'anchore/grype:latest' \
    "docker:${image}"
  log::log "Scanned: ${image}"
done
