#!/usr/bin/env bash

# @description Start the current directory's docker compose project detached, removing orphan containers.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

docker compose up --detach --remove-orphans
