#!/usr/bin/env bash

# @description Run `docker compose logs --follow` in the current directory.
# @noargs
# @stdout Streamed compose service logs.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

docker compose logs --follow
