#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_no_args "$@"

images="$(docker images --all --filter=dangling=true --quiet)"
readonly images
if [[ -n "${images}" ]]; then
  docker rmi "${images}"
fi
