#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if file_exists 'compose.yaml'; then
  docker compose pull
else
  find . -name 'compose.yaml' | sort | while read -r compose_file; do
    compose_dir="$(basename "$(dirname "${compose_file}")")"
    log "Running docker compose pull for: ${compose_dir}"
    docker compose --file "${compose_file}" pull
  done
fi
