#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_at_least_1_arg "$@"
check_at_most_2_args "$@"

temp_file="$(download_to_temp_file "$1")" || exit 1
readonly temp_file
if is_not_empty "${2:-}"; then
  age --decrypt --identity "${AGE_PRIVATE_KEY_FILE}" --output "$2" "${temp_file}"
else
  age --decrypt --identity "${AGE_PRIVATE_KEY_FILE}" "${temp_file}"
fi
