#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_exactly_1_arg "$@"

# Download the input file from Periscope

file="members_for_sign_in_$(date +%Y%m%d_%H%M%S).csv"
readonly file

# fields: last_name, first_name, email, membership_status

python3 -c '
import csv
import sys

# Install the default signal handler.
from signal import signal, SIGPIPE, SIG_DFL

signal(SIGPIPE, SIG_DFL)

reader = csv.reader(sys.stdin)
next(reader) # skip header line
writer = csv.writer(sys.stdout)
for row in reader:
    writer.writerow([row[2], row[0], row[3], row[5]])
' < "$1" | sort >> "${file}"
