#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_exactly_1_arg "$@"

# Download the input file from Periscope

file="migs_for_spoke_$(date +%Y%m%d_%H%M%S).csv"
readonly file
echo 'lastName,firstName,cell' > "${file}"
awk -F',' -v 'OFS=,' '$16 == "Member in Good Standing" && ($7) { print $3, $1, $7 }' "$1" | sort >> "${file}"
