#!/usr/bin/env bash

python3 -c '
import csv
import sys

# Install the default signal handler.
from signal import signal, SIGPIPE, SIG_DFL

signal(SIGPIPE, SIG_DFL)

reader = csv.reader(sys.stdin)
next(reader) # skip header line
writer = csv.writer(sys.stdout)
for row in reader:
    writer.writerow([row[2], row[1], row[0], row[3]])
' | sort
