#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_exactly_1_arg "$@"

# Download the input file from Periscope

readonly last_name_idx=3
readonly first_name_idx=1
readonly phone_number_idx=5
readonly status_idx=6

file="migs_for_spoke_$(date +%Y%m%d_%H%M%S).csv"
readonly file
printf '%s\n' 'last_name,first_name,phone_number' > "${file}"
awk --field-separator ',' \
  --assign 'OFS=,' \
  --assign "status_idx=${status_idx}" \
  --assign "phone_idx=${phone_number_idx}" \
  --assign "last_idx=${last_name_idx}" \
  --assign "first_idx=${first_name_idx}" \
  '$status_idx == "Member in Good Standing" && $phone_idx != "" { print $last_idx, $first_idx, $phone_idx }' \
  "$1" \
  | sort >> "${file}"
