#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

function usage() {
  printf '%s\n' "Usage: ${0##*/} [-d | --dir DIR] DISTRO..." >&2
}

function main() {
  dirs::create "${dir}"
  local distros
  if [[ "$#" -eq 0 ]]; then
    distros=('alpine' 'archlinux' 'debian' 'fedora' 'ubuntu')
  else
    distros=("$@")
  fi
  for distro in "${distros[@]}"; do
    log::log "Dumping /etc from ${distro} to ${dir}/${distro}"
    docker run --rm --volume "${dir}/${distro}:/host" "${distro}:latest" sh -c 'cp -r /etc /host'
    log::log "Dumped /etc from ${distro} to ${dir}/${distro}"
  done
  sudo chown --recursive "${USER}" "${dir}"/*
}

parsed_args="$(getopt --alternative --name "${0##*/}" --options 'd:' --longoptions 'dir:' -- "$@")" || exit 1
readonly parsed_args
# eval is required to re-tokenize the quoted output of getopt
eval set -- "${parsed_args}"
while true; do
  case "$1" in
    -d | --dir)
      dir="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      usage
      log::die "Unexpected option: $1 - this should not happen."
      ;;
  esac
done
readonly dir="${dir:-.}"

main "$@"
