#!/usr/bin/env bash

# @description Run throwaway containers for each given (or default) distro and copy their /etc trees to a host directory.
# @arg $@ distros Optional list of distro image names to dump; defaults to alpine, archlinux, debian, fedora, ubuntu.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

# @description Print usage information to stderr.
# @noargs
function usage() {
  printf '%s\n' "Usage: ${0##*/} [-d | --dir DIR] DISTRO..." >&2
}

# @description Run a throwaway container for each given distro (or a default set) and copy its /etc tree to ${dir}/<distro>.
# @noargs
function main() {
  dirs::create "${dir}"
  local distros
  if args::no_args "$@"; then
    distros=('alpine' 'archlinux' 'debian' 'fedora' 'ubuntu')
  else
    distros=("$@")
  fi
  for distro in "${distros[@]}"; do
    log::log "Dumping /etc from ${distro} to ${dir}/${distro}"
    docker run --rm --volume "${dir}/${distro}:/host" "${distro}:latest" sh -c 'cp -r /etc /host'
    log::log "Dumped /etc from ${distro} to ${dir}/${distro}"
  done
  sudo chown --recursive "${USER}" "${dir}"/*
}

parsed_args="$(getopt --alternative --name "${0##*/}" --options 'd:' --longoptions 'dir:' -- "$@")"
readonly parsed_args
# eval is required to re-tokenize the quoted output of getopt
eval set -- "${parsed_args}"
while true; do
  case "$1" in
    -d | --dir)
      dir="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      usage
      log::die "Unexpected option: $1 - this should not happen."
      ;;
  esac
done
readonly dir="${dir:-.}"

main "$@"
