#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'
trap 'printf "\033[0;31m[%s %s] ERROR: line %s (exit %s): %s\033[0m\n" "$(date +%T)" "${0##*/}" "${LINENO}" "$?" "${BASH_COMMAND}" >&2' ERR

if ((BASH_VERSINFO[0] < 4)); then
  printf 'bash 4+ required\n' >&2
  exit 1
fi

printf '%s\n' "$*" >&2
