#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/../lib/functions.sh"
check_exactly_1_arg "$@"

# Find a file with a pattern in name
find . -type f -iname '*'"$1"'*' -ls
