#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_exactly_1_arg "$@"

# Find a file with a pattern in name
find . -type f -iname '*'"$1"'*' -ls
