#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

find . -iregex '.*\.\(mkv\|mp4\)$' -printf '%P\n' | sort | while read -r video_file; do
  video_info="$(ffprobe "${video_file}" -show_entries 'stream=codec_name,codec_long_name,width,height' -select_streams 'v:0' -loglevel '16' -output_format 'compact=p=0:nk=1')"
  echo "${video_info} | ${video_file}"
done
