#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_no_args "$@"

find . -iregex '.*\.\(mkv\|mp4\)$' -printf '%P\n' | sort | while read -r video_file; do
  echo "${video_file}"
  audio_info="$(
    ffprobe "${video_file}" -show_entries 'stream=index,codec_name,channel_layout:stream_tags=language' -select_streams 'a' -loglevel '16' -output_format 'compact=p=0:nk=1' \
      | awk --field-separator '|' '{ print $1 " | " $4 " | " $2 " | " $3 }'
  )" || exit 1
  echo "${audio_info}"
  echo '---------'
done
