#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

while read -r video_file; do
  resolution_info="$(
    ffprobe "${video_file}" \
      -show_entries 'stream=width,height' \
      -select_streams 'v:0' \
      -loglevel '16' \
      -output_format 'csv=s=x:p=0'
  )"
  printf '%s\n' "${resolution_info%x};${video_file}"
done < <(find . -iregex '.*\.\(mkv\|mp4\)$' -printf '%P\n' | sort)
