#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_most_1_arg "$@"

if [[ "$#" -eq 1 ]]; then
  if [[ "$1" == 'debug' ]]; then
    readonly debug='true'
  else
    log::die "Expected 1 arg: 'debug'"
  fi
else
  readonly debug='false'
fi

while read -r video_file; do
  if [[ "${debug}" == 'true' ]]; then
    log::log "${video_file}"
  fi
  audio_info="$(
    ffprobe "${video_file}" \
      -show_entries 'stream=index,codec_name,channel_layout:stream_tags=language' \
      -select_streams 'a' \
      -loglevel '16' \
      -output_format 'compact=p=0:nk=1' \
      | awk --field-separator '|' '{ print $1 " | " $4 " | " $2 " | " $3 }'
  )" || exit 1
  if grep --quiet --invert-match --fixed-strings '| eng |' <<< "${audio_info}"; then
    printf '%s\n' "${video_file}"
    printf '%s\n' "${audio_info}"
    printf '%s\n' '---------'
  fi
done < <(find . -iregex '.*\.\(mkv\|mp4\)$' -printf '%P\n' | sort)
