#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

find . -iregex '.*\.\(mkv\|mp4\)$' -printf '%P\n' | sort | while read -r video_file; do
  video_info="$(
    ffprobe "${video_file}" -show_entries 'stream=codec_name,width,height' -select_streams 'v:0' -loglevel '16' -output_format 'compact=p=0:nk=1' \
      | awk --field-separator '|' '{ print $2 " | " $3 " | " $1 }'
  )" || exit 1
  readonly video_info
  echo "${video_info} | $(file_size_gb "${video_file}")G | $(dirname "${video_file}") | $(basename "${video_file}")"
done
