#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_exactly_1_arg "$@"

if ! file_exist "$1"; then
  die "$1 does not exist"
fi

if ! is_readable_file "$1"; then
  die "$1 is not readable"
fi

echo "----------"
echo "$1"
echo "----------"
ls -l "$1"
file "$1"
