#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_at_most_1_arg "$@"

if [[ "$#" -eq 0 ]]; then
  readonly dir="."
else
  readonly dir="$1"
fi

find "${dir}" -type f | awk --field-separator '/' '{
  if (NF == 2) print $1;
  else if (NF > 2) print $2;
}' | sort | uniq --count | sort --numeric-sort --reverse
