#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_exactly_1_arg "$@"
readonly INPUT_FILE="$1"

if ! files::exists "${INPUT_FILE}"; then
  log::die "${INPUT_FILE} does not exist"
fi

if ! files::is_readable "${INPUT_FILE}"; then
  log::die "${INPUT_FILE} is not readable"
fi

printf '%s\n' "----------"
printf '%s\n' "${INPUT_FILE}"
printf '%s\n' "----------"
ls --format=long "${INPUT_FILE}"
file "${INPUT_FILE}"
