#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0

function usage() {
  printf '%s\n' "Usage: ${0##*/} [-d | --dir DIR] FILE..." >&2
}

parsed_args="$(getopt --alternative --name "${0##*/}" --options 'd:' --longoptions 'dir:' -- "$@")" || exit 1
readonly parsed_args
# eval is required to re-tokenize the quoted output of getopt
eval set -- "${parsed_args}"
while true; do
  case "$1" in
    -d | --dir)
      dir="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      usage
      die "Unexpected option: $1 - this should not happen."
      ;;
  esac
done
readonly dir="${dir:-.}"

check_at_least_1_arg "$@"

for file in "$@"; do
  find -L "${dir}" -samefile "${file}" -exec printf '%s\n' "${file} {}" \; 2> '/dev/null' || true
done | sort | column --table --table-columns 'FILE,LINK'
