#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"

function usage() {
  echo "Usage: ${0##*/} [-d | --dir DIR] FILE..." >&2
}

parsed_args="$(getopt --alternative --name "${0##*/}" --options 'd:' --longoptions 'dir:' -- "$@")" || exit 1
readonly parsed_args
eval set -- "${parsed_args}"
while true; do
  case "$1" in
    -d | --dir)
      readonly dir="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      usage
      die "Unexpected option: $1 - this should not happen."
      ;;
  esac
done
readonly dir="${dir:-.}"

check_at_least_1_arg "$@"

for file; do
  find -L "${dir}" -samefile "${file}" -exec echo "${file} {}" \; 2> '/dev/null' || true
done | sort | column --table --table-columns 'FILE,LINK'
