#!/usr/bin/env bash

# @description Find every symlink under a given directory (default `.`) that points at any of the named files and print a FILE/LINK table.
# @arg $@ files One or more target file paths to search for.
# @stdout Table with columns FILE and LINK listing each match.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

# @description Print usage information to stderr.
# @noargs
function usage() {
  printf '%s\n' "Usage: ${0##*/} [-d | --dir DIR] FILE..." >&2
}

# @description Find every symlink under ${dir} that points at any of the given files and print a FILE/LINK table.
# @arg $@ target file paths to search for
function main() {
  for file in "$@"; do
    find -L "${dir}" -samefile "${file}" -exec printf '%s\n' "${file} {}" \; 2> '/dev/null' || true
  done | sort | column --table --table-columns 'FILE,LINK'
}

parsed_args="$(getopt --alternative --name "${0##*/}" --options 'd:' --longoptions 'dir:' -- "$@")"
readonly parsed_args
# eval is required to re-tokenize the quoted output of getopt
eval set -- "${parsed_args}"
while true; do
  case "$1" in
    -d | --dir)
      dir="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      usage
      log::die "Unexpected option: $1 - this should not happen."
      ;;
  esac
done
readonly dir="${dir:-.}"

args::check_at_least_1_arg "$@"

main "$@"
