#!/usr/bin/env bash

# @description Grant cap_net_raw to every `ping` binary under /nix/store so non-root users can run ping on NixOS.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

find '/nix/store' -type 'f' -name 'ping' -exec sudo setcap 'cap_net_raw+ep' {} \;
