#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_no_args "$@"

find '/nix/store' -type 'f' -name 'ping' -exec sudo setcap 'cap_net_raw+ep' {} \;
