#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/../lib/functions.sh"
check_no_args "$@"

echo 'LC_ALL=en_US.UTF-8' | sudo tee --append '/etc/environment'
echo 'en_US.UTF-8 UTF-8' | sudo tee --append '/etc/locale.gen'
echo 'LANG=en_US.UTF-8' | sudo tee --append '/etc/locale.conf'
sudo locale-gen 'en_US.UTF-8'
