#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

root_append_to_file '/etc/environment' 'LC_ALL=en_US.UTF-8'
root_append_to_file '/etc/locale.gen' 'en_US.UTF-8 UTF-8'
root_append_to_file '/etc/locale.conf' 'LANG=en_US.UTF-8'
sudo locale-gen 'en_US.UTF-8'
