#!/usr/bin/env bash

# @description Configure system locale to en_US.UTF-8 by appending to /etc/environment, /etc/locale.gen, /etc/locale.conf and running locale-gen.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

files::root_append_to '/etc/environment' 'LC_ALL=en_US.UTF-8'
files::root_append_to '/etc/locale.gen' 'en_US.UTF-8 UTF-8'
files::root_append_to '/etc/locale.conf' 'LANG=en_US.UTF-8'
sudo locale-gen 'en_US.UTF-8'
