#!/usr/bin/env bash

# @description Transcode every .flac file under the current directory in-place to V0 MP3 via flac2mp3.pl, using all CPU cores.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

flac2mp3.pl --quiet --lameargs='-V0 --noreplaygain --nohist --quiet' --processes="$(nproc)" . .
