#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/../lib/functions.sh"
check_no_args "$@"

flac2mp3.pl --quiet --lameargs='-V0 --noreplaygain --nohist --quiet' --processes="$(nproc)" . .
