#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/../lib/functions.sh"
check_for_var 'FILE_MANAGER'

if [[ "$#" -eq 0 ]]; then
  "${FILE_MANAGER}" . > /dev/null 2>&1 &
else
  "${FILE_MANAGER}" "$@" > /dev/null 2>&1 &
fi
disown
