#!/usr/bin/env bash

# @description Open the first available file manager (xdg-open, lf, ranger, or fff) on the given directory or the current directory.
# @arg $1 dir Optional directory to open; defaults to `.`.
# @exitcode 1 No supported file manager is installed.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_at_most_1_arg "$@"

if commands::executable_exists 'xdg-open'; then
  fm='xdg-open'
  gui='y'
elif commands::executable_exists 'lf'; then
  fm='lf'
  gui='n'
elif commands::executable_exists 'ranger'; then
  fm='ranger'
  gui='n'
elif commands::executable_exists 'fff'; then
  fm='fff'
  gui='n'
else
  log::die "Could not find a file manager"
fi
readonly fm gui

if args::no_args "$@"; then
  readonly dir='.'
else
  readonly dir="$1"
fi

if [[ "${gui}" == 'y' ]]; then
  misc::exec_gui "${fm}" "${dir}"
else
  "${fm}" "${dir}"
fi
