#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_at_least_1_arg "$@"
check_for_stdin

# ex:
# echo -e 'foo bar\nbaz' | for-each-line echo
# runs (in sequence):
# echo foo bar
# echo baz
xargs --max-args=1 --delimiter='\n' "$@"
