#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_at_least_1_arg "$@"
check_for_stdin

# echo -e 'foo bar\nbaz' | for-each-parallel echo
# runs (in parallel):
# echo foo
# echo bar
# echo baz
xargs --max-procs="$(nproc)" --max-args=1 "$@"
