#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_at_least_1_arg "$@"

mapfile -t containers < <(docker ps --format '{{.Names}}' | sort)
for container in "${containers[@]}"; do
  docker exec "${container}" "$@" | while read -r line; do echo "${container} ${line}"; done
done | column --table --table-columns 'CONTAINER,RESULT' --table-columns-limit 2
