#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_at_least_1_arg "$@"
check_for_stdin

# ex:
# printf '%s\n' 'foo bar' 'baz' | for-each printf '%s\n'
# runs (in sequence):
# printf '%s\n' foo
# printf '%s\n' bar
# printf '%s\n' baz
xargs --no-run-if-empty --max-args=1 "$@"
