#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_at_least_1_arg "$@"
## TODO check this
check_for_stdin

# ex:
# echo -e 'foo bar\nbaz' | for-each-line-parallel echo
# runs (in parallel):
# echo foo bar
# echo baz
xargs --max-procs="$(nproc)" --max-args=1 --delimiter='\n' "$@"
