#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_least_1_arg "$@"

mapfile -t containers < <(docker ps --format '{{.Names}}' | sort)
for container in "${containers[@]}"; do
  while read -r line; do
    printf '%s\n' "${container} ${line}"
  done < <(docker exec "${container}" "$@")
done | column --table --table-columns 'CONTAINER,RESULT' --table-columns-limit 2
