#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/../lib/functions.sh"
check_at_least_1_arg "$@"
## TODO check this
check_for_stdin

# echo -e 'foo bar\nbaz' | for-each-parallel echo
# runs (in parallel):
# echo foo
# echo bar
# echo baz
xargs --max-procs="$(nproc)" --max-args=1 "$@"
