#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_at_least_1_arg "$@"
check_for_stdin

# ex:
# echo -e 'foo bar\nbaz' | for-each-line echo
# runs (in sequence):
# echo foo bar
# echo baz
xargs --no-run-if-empty --max-args=1 --delimiter='\n' "$@"
