#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_least_1_arg "$@"
args::check_for_stdin

# ex:
# printf '%s\n' 'foo bar' 'baz' | for-each-line-parallel printf '%s\n'
# runs (in parallel):
# printf '%s\n' 'foo bar'
# printf '%s\n' 'baz'
xargs --no-run-if-empty --max-procs="$(nproc)" --max-args=1 --delimiter='\n' "$@"
