#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

readonly keys_dir="${HOME}/.keys"
dirs::create "${keys_dir}"

readonly age_key_file="${keys_dir}/age.key"
if ! files::exists "${age_key_file}"; then
  log::log "Downloading: ${age_key_file}"
  temp_file="$(downloads::download_to_temp_file 'https://raw.githubusercontent.com/rvenutolo/crypt/main/keys/age.key')"
  if [[ -s "${temp_file}" ]]; then
    log::log "Decrypting: ${age_key_file}"
    until age --decrypt --output "${age_key_file}" "${temp_file}"; do :; done
  else
    log::die "age key file content is empty"
  fi
fi

for filename in 'id_ed25519' 'id_ed25519.pub'; do
  key_file="${keys_dir}/${filename}"
  if ! files::exists "${key_file}"; then
    log::log "Downloading: ${key_file}"
    temp_file="$(downloads::download_to_temp_file "https://raw.githubusercontent.com/rvenutolo/crypt/main/keys/${filename}")"
    if [[ -s "${temp_file}" ]]; then
      log::log "Decrypting: ${key_file}"
      age --decrypt --identity "${age_key_file}" --output "${key_file}" "${temp_file}"
    else
      log::die "${filename} content is empty"
    fi
  fi
done

mapfile -t urls < <(
  downloads::download_and_cat 'https://api.github.com/repos/rvenutolo/crypt/contents/keys' \
    | jq --raw-output '.[].download_url'
)
for url in "${urls[@]}"; do
  filename="$(basename "${url}")"
  if [[ "${filename}" == 'age.key' || "${filename}" == 'id_ed25519' || "${filename}" == 'id_ed25519.pub' ]]; then
    continue
  fi
  key_file="${keys_dir}/${filename}"
  if ! files::exists "${key_file}" && prompt::ny "Download ${filename}?"; then
    log::log "Downloading: ${filename}"
    temp_file="$(downloads::download_to_temp_file "https://raw.githubusercontent.com/rvenutolo/crypt/main/keys/${filename}")"
    if [[ -s "${temp_file}" ]]; then
      log::log "Decrypting: ${key_file}"
      age --decrypt --identity "${age_key_file}" --output "${key_file}" "${temp_file}"
    else
      log::die "${filename} content is empty"
    fi
  fi
done

find "${keys_dir}" -type 'd' -exec chmod 700 {} \;
find "${keys_dir}" -type 'f' -exec chmod 600 {} \;
