#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if prompt_ny 'This will sign ALL commits (without checking commit authors). Continue?'; then
  FILTER_BRANCH_SQUELCH_WARNING='1' git filter-branch --force --commit-filter 'git commit-tree --gpg-sign "$@";'
fi

log "Check the log, then push changes with: git push --force --tags origin 'refs/heads/*'"