#!/usr/bin/env bash

# @description Mark the given tracked files with `git update-index --skip-worktree` so local changes are ignored.
# @arg $@ files One or more tracked file paths to mark skip-worktree.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_at_least_1_arg "$@"

git update-index --skip-worktree "$@"
