#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

old_email="$(prompt::for_value 'Email address to replace')"
readonly old_email
new_email="$(prompt::for_value 'New email address')"
readonly new_email
new_name="$(prompt::for_value 'New name')"
readonly new_name

FILTER_BRANCH_SQUELCH_WARNING='1' git filter-branch --force --env-filter "
OLD_EMAIL='${old_email}'
CORRECT_NAME='${new_name}'
CORRECT_EMAIL='${new_email}'
if [ \"\$GIT_COMMITTER_EMAIL\" = \"\$OLD_EMAIL\" ]
then
    export GIT_COMMITTER_NAME=\"\$CORRECT_NAME\"
    export GIT_COMMITTER_EMAIL=\"\$CORRECT_EMAIL\"
fi
if [ \"\$GIT_AUTHOR_EMAIL\" = \"\$OLD_EMAIL\" ]
then
    export GIT_AUTHOR_NAME=\"\$CORRECT_NAME\"
    export GIT_AUTHOR_EMAIL=\"\$CORRECT_EMAIL\"
fi
" --tag-name-filter cat -- --branches --tags

log::log "Check the log, then push changes with: git push --force --tags origin 'refs/heads/*'"
