#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_no_args "$@"

(
  while read -r user_email; do
    printf '%s\n' "$(git log --author="${user_email}" --oneline | wc --lines) ${user_email}"
  done < <(git log --format='%ae' | sort --unique)
) | column --table --table-columns-limit '2' --output-separator ' | ' --table-right '1'
