#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

old_email="$(prompt_for_value 'Email address to replace')" || exit 1
readonly old_email
new_email="$(prompt_for_value 'New email address')" || exit 1
readonly new_email
new_name="$(prompt_for_value 'New name')" || exit 1
readonly new_name

FILTER_BRANCH_SQUELCH_WARNING='1' git filter-branch --force --env-filter "
OLD_EMAIL='${old_email}'
CORRECT_NAME='${new_name}'
CORRECT_EMAIL='${new_email}'
if [ \"\$GIT_COMMITTER_EMAIL\" = \"\$OLD_EMAIL\" ]
then
    export GIT_COMMITTER_NAME=\"\$CORRECT_NAME\"
    export GIT_COMMITTER_EMAIL=\"\$CORRECT_EMAIL\"
fi
if [ \"\$GIT_AUTHOR_EMAIL\" = \"\$OLD_EMAIL\" ]
then
    export GIT_AUTHOR_NAME=\"\$CORRECT_NAME\"
    export GIT_AUTHOR_EMAIL=\"\$CORRECT_EMAIL\"
fi
" --tag-name-filter cat -- --branches --tags

log "Check the log, then push changes with: git push --force --tags origin 'refs/heads/*'"
