#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_least_1_arg "$@"

git update-index --skip-worktree "$@"
