#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_least_1_arg "$@"

log::log "Googling: $*"
readonly search="${*// /%20}"
xdg-open "https://www.google.com/search?q=${search}" > '/dev/null' 2>&1 &
disown
