#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"

# remove this dir from the path so executing `gradle` doesn't execute this script
path_remove "$(this_script_dir)"

dir="$PWD"
project_root="$PWD"
while [[ "$dir" != / ]]; do
  if [[ -f "$dir/settings.gradle" || -f "$dir/settings.gradle.kts" || -f "$dir/gradlew" ]]; then
    readonly project_root="$dir"
    break
  fi
  dir="$(dirname -- "${dir}")"
done
readonly project_root

if [[ -x "$project_root/gradlew" ]]; then
  log 'Executing gradlew instead of gradle'
  "${project_root}/gradlew" "$@"
else
  gradle "$@"
fi
