#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"

# remove this dir from the path so executing `gradle` doesn't execute this script
path_remove "$(this_script_dir)"

dir="${PWD}"
project_root="${PWD}"
while [[ "${dir}" != / ]]; do
  if file_exists "${dir}/settings.gradle" || file_exists "${dir}/settings.gradle.kts" || file_exists "${dir}/gradlew"; then
    readonly project_root="${dir}"
    break
  fi
  dir="$(dirname -- "${dir}")" || exit 1
done
readonly project_root

if [[ -x "${project_root}/gradlew" ]]; then
  log 'Executing gradlew instead of gradle'
  "${project_root}/gradlew" "$@"
else
  gradle "$@"
fi
