#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

# remove this dir from the path so executing `gradle` doesn't execute this script
path::remove "$(misc::this_script_dir)"

dir="${PWD}"
project_root="${PWD}"
while [[ "${dir}" != / ]]; do
  if files::exists "${dir}/settings.gradle" \
    || files::exists "${dir}/settings.gradle.kts" \
    || files::exists "${dir}/gradlew"; then
    readonly project_root="${dir}"
    break
  fi
  dir="$(dirname -- "${dir}")"
done
readonly project_root

if files::is_executable "${project_root}/gradlew"; then
  log::log 'Executing gradlew instead of gradle'
  "${project_root}/gradlew" "$@"
else
  gradle "$@"
fi
