#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"

if stdin_exists; then
  check_at_most_1_arg "$@"
  header_line="$(first_line)" || exit 1
  if [[ -n "${1:-}" ]]; then
    readonly delimiter="$1"
  fi
else
  check_at_least_1_arg "$@"
  check_at_most_2_args "$@"
  header_line="$(cat "$1" | first_line)" || exit 1
  if [[ -n "${2:-}" ]]; then
    readonly delimiter="$2"
  fi
fi
readonly header_line

if [[ -z "${delimiter+x}" ]]; then
  if contains_exactly ';' <<< "${header_line}"; then
    readonly delimiter=';'
  elif contains_exactly ',' <<< "${header_line}"; then
    readonly delimiter=','
  elif contains_exactly '\t' <<< "${header_line}"; then
    readonly delimiter='\t'
  elif contains_exactly '|' <<< "${header_line}"; then
    readonly delimiter='|'
  elif contains_exactly ':' <<< "${header_line}"; then
    readonly delimiter=':'
  else
    readonly delimiter=','
  fi
fi

tr "${delimiter}" '\n' <<< "${header_line}" | cat --number
