#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_at_least_1_arg "$@"
check_at_most_2_args "$@"

readonly input_file="$1"
if [[ -n "${2:-}" ]]; then
  readonly delimiter="$2"
else
  readonly delimiter=','
fi

head --lines 1 "$1" | tr "${delimiter}" '\n' | cat --number
