#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_least_1_arg "$@"

for file in "$@"; do
  dirname="$(dirname -- "${file}")" || exit 1
  filename="$(basename -- "${file}")" || exit 1
  target_file="${dirname}/.${filename}"
  mv -- "${file}" "${target_file}"
  log::log "${file} -> ${target_file}"
done
