#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_no_args "$@"

home-manager switch --flake "${HOME_MANAGER_DIR}"
home-manager-generations-diff
