#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

home-manager generations | head --lines=2 | tac | cut --delimiter=' ' --fields='7' | xargs --no-run-if-empty nix store diff-closures
