#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

home-manager switch --flake "${HOME_MANAGER_DIR}"
home-manager-generations-diff
