#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

home-manager switch --flake "${HOME_MANAGER_DIR}" --option download-buffer-size 524288000
home-manager-generations-diff
