#!/usr/bin/env bash

# @description Run periodic Nix store maintenance: garbage-collect generations older than 10 days and optimise the store.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

nix-collect-garbage --delete-older-than 10d
nix-store --optimise
