#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

write-home-manager-packages
nix flake update "${HOME_MANAGER_DIR}"
home-manager-switch
