#!/usr/bin/env bash

# @description Update the home-manager flake (optionally regenerating the packages file), switch to it, and offer to run maintenance.
# @arg $@ args Optional flags; `--no-write-packages` skips regenerating the packages file. Remaining args are forwarded to `write-home-manager-packages`.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0

WRITE_PACKAGES=1
EXTRA_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-write-packages)
      WRITE_PACKAGES=''
      shift
      ;;
    *)
      EXTRA_ARGS+=("$1")
      shift
      ;;
  esac
done
readonly WRITE_PACKAGES
readonly EXTRA_ARGS

if strings::is_not_empty "${WRITE_PACKAGES}"; then
  write-home-manager-packages "${EXTRA_ARGS[@]}"
else
  log::log "Skipping writing packages file"
fi

nix-channel --update
nix flake update --flake "${HOME_MANAGER_DIR}"
home-manager-switch

if prompt::ny 'Run home-manager-maintenance?'; then
  home-manager-maintenance
fi
