#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

http::curl --ipv4 ipinfo.io \
  | jq 'del(.readme)' \
  | jq --raw-output 'to_entries[]|"\(.key)|\(.value)"' \
  | column --table --separator '|'
