#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_no_args "$@"

curl --disable --silent --show-error --location ipinfo.io \
  | jq 'del(.readme)' \
  | jq -r 'to_entries[]|"\(.key)|\(.value)"' \
  | column --table --separator '|'
