#!/usr/bin/env bash

# @description Fetch this host's public IPv4 info from ipinfo.io and print it as a two-column key/value table.
# @noargs
# @stdout Tab-aligned key/value table of ipinfo.io fields.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

http::curl --ipv4 ipinfo.io \
  | jq 'del(.readme)' \
  | jq --raw-output 'to_entries[]|"\(.key)|\(.value)"' \
  | column --table --separator '|'
