#!/usr/bin/env bash

# @description Convert a dotted-quad IPv4 address to its 32-bit integer representation.
# @arg $1 ipv4 Dotted-quad IPv4 address (e.g. 192.168.0.1).
# @stdout The integer form of the address.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_exactly_1_arg "$@"

ip::ipv4_to_num "$1"
