#!/usr/bin/env bash

# @description Print all available Temurin JDK major version numbers, sorted numerically.
# @noargs
# @stdout Major version numbers, one per line.
# @exitcode 0 success

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

sdkman_jdks::get_available_tem_jdk_major_versions
