#!/usr/bin/env bash

# @description Print all installed Temurin JDK entries in semicolon-delimited format.
# @noargs
# @stdout Lines with fields: major;version;artifact-id;installed('y'/'n').
# @exitcode 0 success

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

sdkman_jdks::get_formatted_installed_tem_jdks
