#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_exactly_1_arg "$@"

unzip -p "$1" 'META-INF/MANIFEST.MF' | grep --fixed-strings 'Build-Jdk-Spec'
