#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_exactly_1_arg "$@"

unzip -p "$1" 'META-INF/MANIFEST.MF' | grep --fixed-strings 'Build-Jdk-Spec'
