#!/usr/bin/env bash

# @description Show error-priority (and worse) journal entries from the previous boot.
# @noargs
# @stdout `journalctl` output filtered to priority<=err for the previous boot.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

journalctl --priority=3 --catalog --boot=-1
