#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

# remove this dir from the path so executing `kate` doesn't execute this script
path::remove "$(misc::this_script_dir)"

kate "$@" > '/dev/null' 2>&1 &
disown
