#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.bash"

# remove this dir from the path so executing `kate` doesn't execute this script
path_remove "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

kate "$@" > /dev/null 2>&1 &
disown
