#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

# chezmoi external files stuff should get this file,
# which is a script that should have one function: kitty_keys
readonly kitty_keys_file="${XDG_CONFIG_HOME}/kitty/kitty_keys.sh"
if is_readable_files "${kitty_keys_file}"; then
  # shellcheck disable=SC1090 # kitty_keys_file path is dynamic at runtime
  source "${kitty_keys_file}"
  kitty_keys
else
  log::die "${kitty_keys_file} is not a readable file"
fi
