#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_no_args "$@"

# chezmoi external files stuff should get this file,
# which is a script that should have one function: kitty_keys
readonly kitty_keys_file="${XDG_CONFIG_HOME}/kitty/kitty_keys.sh"
if is_readable_files "${kitty_keys_file}"; then
  #shellcheck disable=SC1090
  source "${kitty_keys_file}"
  kitty_keys
else
  die "${kitty_keys_file} is not a readable file"
fi
