#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.sh"
check_no_args "$@"
check_for_stdin

## handy for counting duplicated lines in a file or listing
sort | uniq --count | sort --numeric-sort --reverse
