#!/usr/bin/env bash

# @description Download (via etag cache) and run the latest linpeas linux-amd64 binary, writing its output to a timestamped file under $HOME.
# @arg $@ args Optional arguments forwarded to the linpeas binary.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

readonly url='https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas_linux_amd64'
readonly linpeas_file="${XDG_DATA_HOME}/linpeas"
linpeas_output="${HOME}/linpeas_$(date +%Y%m%d-%H%M%S).txt"
readonly linpeas_output

dirs::create "$(dirname "${linpeas_file}")"
etag-dl "${url}" "${linpeas_file}"
chmod +x "${linpeas_file}"

log::log "This can take a long time"
log::log "Writing output to: ${linpeas_output}"
"${linpeas_file}" "$@" > "${linpeas_output}"
log::log "Wrote output to: ${linpeas_output}, read it with 'less --raw-control-chars ${linpeas_output}'"
