#!/usr/bin/env bash

# @description Print this host's primary local (LAN) IP address.
# @noargs
# @stdout The primary local IPv4 address.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

network::local_ip
