#!/usr/bin/env bash

# @description Print the CIDR of the primary local network attached to this host.
# @noargs
# @stdout The local network in CIDR notation (e.g. `192.168.1.0/24`).

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

network::local_network
