#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

if args::stdin_exists; then
  args::check_no_args "$@"
  tr '[:upper:]' '[:lower:]'
else
  args::check_at_least_1_arg "$@"
  for file in "$@"; do
    dirname="$(dirname -- "${file}")"
    filename="$(basename -- "${file}")"
    lower_filename="$(printf '%s\n' "${filename}" | tr '[:upper:]' '[:lower:]')"
    target_file="${dirname}/${lower_filename}"
    if [[ "${lower_filename}" != "${filename}" ]]; then
      mv -- "${file}" "${target_file}"
      log::log "${file} -> ${target_file}"
    else
      log::log "${file} not renamed"
    fi
  done
fi
