#!/usr/bin/env bash

# @description Open the man page for a command and jump to the description of a specific option/switch.
# @arg $1 command Command whose man page should be opened.
# @arg $2 switch Option/switch name to search for in the man page.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_exactly_2_args "$@"
readonly COMMAND="$1"
readonly SWITCH="$2"

man "${COMMAND}" | less --pattern="^ +${SWITCH}"
