#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

find . -name '*.mkv' | sort | while read -r mkv_file; do
  echo "$(basename "${mkv_file}")"
  ffprobe "${mkv_file}" -show_entries stream=index:stream_tags=language -select_streams a -v 0 -of compact=p=0:nk=1
done
