#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

find . -name '*.mkv' | sort | while read -r mkv_file; do
  foreign_audio="$(ffprobe "${mkv_file}" -show_entries stream=index:stream_tags=language -select_streams a -v 0 -of compact=p=0:nk=1 | grep --invert-match '|eng$')"
  if [[ -z "${foreign_audio}" ]]; then
    echo '---------'
    echo "$(basename "${mkv_file}")"
    ffprobe "${mkv_file}" -show_entries stream=index:stream_tags=language -select_streams a -v 0 -of compact=p=0:nk=1
  fi
done
