#!/usr/bin/env bash

# @description Launch the real `mpv` detached from the terminal, forwarding all arguments.
# @arg $@ args Arguments forwarded verbatim to the underlying `mpv` binary.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"

# remove this dir from the path so executing `mpv` doesn't execute this script
path::remove "$(misc::this_script_dir)"

misc::exec_gui mpv "$@"
