#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0

# remove this dir from the path so executing `mpv` doesn't execute this script
path_remove "$(this_script_dir)"

mpv "$@" > '/dev/null' 2>&1 &
disown
