#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

# remove this dir from the path so executing `mvn` doesn't execute this script
path::remove "$(misc::this_script_dir)"

dir="${PWD}"
project_root="${PWD}"
while [[ "${dir}" != / ]]; do
  if files::exists "${dir}/pom.xml" || files::exists "${dir}/mvnw"; then
    readonly project_root="${dir}"
    break
  fi
  dir="$(dirname -- "${dir}")"
done
readonly project_root

if [[ -x "${project_root}/mvnw" ]]; then
  log::log 'Executing mvnw instead of mvn'
  exec "${project_root}/mvnw" "$@"
else
  exec mvn "$@"
fi
