#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

# $1 = pom file
function get_sources() {
  mvn -f "$1" dependency:sources dependency:resolve -Dclassifier='javadoc'
}

if file_exists 'pom.xml'; then
  get_sources './pom.xml'
else
  pom_files="$(find . -name 'pom.xml' | sort)"
  readonly pom_files
  for pom_file in ${pom_files[@]}; do
    get_sources "${pom_file}"
  done
fi
