#!/usr/bin/env bash

# @description Run `mvn versions:display-dependency-updates` against the current Maven project.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

mvn versions:display-dependency-updates
