#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

# $1 = pom file
function get_sources() {
  mvn --file "$1" \
    org.apache.maven.plugins:maven-dependency-plugin:resolve-sources \
    org.apache.maven.plugins:maven-dependency-plugin:resolve \
    -Dclassifier=javadoc
}

pom_files="$(mvn::list_pom_files)" || exit 1
readonly pom_files
while IFS='' read -r pom_file; do
  get_sources "${pom_file}"
done <<< "${pom_files}"
