#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

mvn com.github.ekryd.sortpom:sortpom-maven-plugin:sort \
  -Dsort.keepBlankLines=true \
  -Dsort.predefinedSortOrder='recommended_2008_06' \
  -Dsort.encoding='UTF-8' \
  -Dsort.lineSeparator='\n' \
  -Dsort.nrOfIndentSpace=4 \
  -Dsort.sortDependencies=scope,groupId,artifactId
