#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

mvn com.github.ekryd.sortpom:sortpom-maven-plugin:sort \
  -Dsort.keepBlankLines=true-Dsort.predefinedSortOrder='recommended_2008_06' \
  -Dsort.encoding='UTF-8' \
  -Dsort.lineSeparator='\n' \
  -Dsort.nrOfIndentSpace=4
