#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/../lib/functions.sh"
check_no_args "$@"

mvn com.github.ekryd.sortpom:sortpom-maven-plugin:sort \
  -Dsort.keepBlankLines=true-Dsort.predefinedSortOrder='recommended_2008_06' \
  -Dsort.encoding='UTF-8' \
  -Dsort.lineSeparator='\n' \
  -Dsort.nrOfIndentSpace=4 \
  -Dsort.sortDependencies=scope,groupId,artifactId
