#!/usr/bin/env bash

# @description List all SNAPSHOT dependencies in the current Maven project via `mvn dependency:tree`.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

mvn dependency:tree -Dincludes=:::*-SNAPSHOT
