#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_least_1_arg "$@"

for file in "$@"; do
  if [[ -e "${file}" ]]; then
    log::die "${file} already exists"
  fi
  cat > "${file}" << 'EOF'
#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"
EOF
  chmod +x "${file}"
done
