#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_at_least_1_arg "$@"

for file; do
  if [[ -e "${file}" ]]; then
    die "${file} already exists"
  fi
  (
    echo '#!/usr/bin/env bash'
    echo ''
    echo 'set -euo pipefail'
  ) > "${file}"
  chmod +x "${file}"
done
