#!/usr/bin/env bash

# @description Convert a 32-bit unsigned integer into its dotted-quad IPv4 representation.
# @arg $1 number Integer in the range 0..4294967295 to convert.
# @stdout The corresponding IPv4 address in dotted-quad notation.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_exactly_1_arg "$@"

ip::num_to_ipv4 "$1"
