#!/usr/bin/env bash

# @description Grant world read/write on all `/dev/hidraw*` devices so the NuPhy.io web configurator can access the keyboard.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

sudo chmod a+rw /dev/hidraw*
