#!/usr/bin/env bash

# @description Print each entry of `$PATH` on its own line.
# @noargs
# @stdout One `$PATH` entry per line, in order.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

tr ':' '\n' <<< "${PATH}"
