#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

if args::stdin_exists; then
  args::check_no_args "$@"
  highlight --out-format=ansi --force
else
  args::check_at_least_1_arg "$@"
  for file in "$@"; do
    case "${file}" in
      *.md) glow "${file}" ;;
      *) highlight --out-format=ansi --force "${file}" ;;
    esac
  done
fi
