#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

if args::stdin_exists; then
  args::check_no_args "$@"
  highlight --out-format=ansi --force | less --raw-control-chars
else
  args::check_exactly_1_arg "$@"
  case "$1" in
    *.md) glow "$1" | less --raw-control-chars ;;
    *) highlight --out-format=ansi --force "$1" | less --raw-control-chars ;;
  esac
fi
