#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

log::log "Plex: http://127.0.0.1:8888/web"
ssh -L 8888:127.0.0.1:32400 100.123.5.106
