#!/usr/bin/env bash

# @description Open an SSH tunnel from local port 8888 to the Plex server's web UI on port 32400.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

log::log "Plex: http://127.0.0.1:8888/web"
ssh -L 8888:127.0.0.1:32400 100.123.5.106
