#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

images="$(podman images --all --filter=dangling=true --quiet)" || exit 1
readonly images
if [[ -n "${images}" ]]; then
  podman rmi "${images}"
fi
