#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

containers="$(docker ps --filter=status=exited --filter=status=created --quiet)"
readonly containers
if [[ -n "${containers}" ]]; then
  podman rm "${containers}"
fi
