#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.bash"
check_no_args "$@"

containers="$(docker ps --filter=status=exited --filter=status=created --quiet)"
readonly containers
if [[ -n "${containers}" ]]; then
  podman rm "${containers}"
fi
