#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.sh"
check_no_args "$@"

readonly images="$(docker images --all --filter=dangling=true --quiet)"
if [[ -n "${images}" ]]; then
  podman rmi "${images}"
fi
