#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

## get top process eating cpu ##
ps auxf | sort --numeric-sort --reverse --key=3
