#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_no_args "$@"

## get top process eating cpu ##
ps auxf | sort --numeric-sort --reverse --key=3
