#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_no_args "$@"

## get top process eating memory
ps auxf | sort --numeric-sort --reverse --key=4
