#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_at_least_2_args "$@"
check_at_most_3_args "$@"

if [[ "$#" -eq 3 ]]; then
  readonly num_output="$3"
else
  readonly num_output=1
fi

shuf --input-range "$1-$2" --head-count "${num_output}"
