#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_least_2_args "$@"
args::check_at_most_3_args "$@"
readonly MIN="$1"
readonly MAX="$2"

if [[ "$#" -eq 3 ]]; then
  readonly NUM_OUTPUT="$3"
else
  readonly NUM_OUTPUT=1
fi

shuf --input-range "${MIN}-${MAX}" --head-count "${NUM_OUTPUT}"
