#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_no_args "$@"

shopt -s nocaseglob
for readme_file in readme*; do
  if is_readable_file "${readme_file}"; then
    printf '%s\n' "----------"
    printf '%s\n' "${readme_file}"
    printf '%s\n' "----------"
    if executable_exists 'glow'; then
      glow "${readme_file}"
    else
      cat "${readme_file}"
    fi
  fi
done
