#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

shopt -s nocaseglob
for readme_file in readme*; do
  if files::is_readable "${readme_file}"; then
    printf '%s\n' "----------"
    printf '%s\n' "${readme_file}"
    printf '%s\n' "----------"
    if commands::executable_exists 'glow'; then
      glow "${readme_file}"
    else
      cat "${readme_file}"
    fi
  fi
done
