#!/usr/bin/env bash

# @description Strip ANSI escape sequences from stdin and write the cleaned text to stdout.
# @noargs
# @stdout Input text with ANSI escape sequences removed.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"
args::check_for_stdin

text::remove_ansi
