#!/usr/bin/env bash

# @description Remove unprintable characters (keeping newlines) from stdin and write the result to stdout.
# @noargs
# @stdout Input text with non-printable characters stripped.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"
args::check_for_stdin

tr --complement --delete '[:print:]\n'
