#!/usr/bin/env bash

# @description Restart `systemd-resolved.service` if it is enabled on this host.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

systemctl::restart_system_service_if_enabled 'systemd-resolved.service'
