#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_no_args "$@"

read -r -p 'Email address to replace: ' old_email
read -r -p 'New email address: ' new_email
read -r -p 'New name: ' new_name

# adapted from https://help.github.com/articles/changing-author-info/
git filter-branch --force --env-filter "
OLD_EMAIL='${old_email}'
CORRECT_NAME='${new_name}'
CORRECT_EMAIL='${new_email}'
if [ \"\$GIT_COMMITTER_EMAIL\" = \"\$OLD_EMAIL\" ]
then
    export GIT_COMMITTER_NAME=\"\$CORRECT_NAME\"
    export GIT_COMMITTER_EMAIL=\"\$CORRECT_EMAIL\"
fi
if [ \"\$GIT_AUTHOR_EMAIL\" = \"\$OLD_EMAIL\" ]
then
    export GIT_AUTHOR_NAME=\"\$CORRECT_NAME\"
    export GIT_AUTHOR_EMAIL=\"\$CORRECT_EMAIL\"
fi
" --tag-name-filter cat -- --branches --tags

log "Check the log, then push changes with: git push --force --tags origin 'refs/heads/*'"
