#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_at_least_1_arg "$@"

rsync-bak \
  --exclude '.cache/' \
  --exclude '.groovy/' \
  --exclude '.ivy2/' \
  --exclude '.local/share/baloo/' \
  --exclude '.local/share/Trash/' \
  --exclude '.local/share/stack/' \
  --exclude '.m2/repository/' \
  --exclude '.stack/' \
  --exclude 'snap/' \
  --exclude 'VMs/' \
  "$HOME" "$@"
