#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.bash"
check_at_least_1_arg "$@"

rsync \
  --archive \
  --itemize-changes \
  --human-readable \
  --executability \
  --partial \
  --progress \
  --atimes \
  --stats \
  --links \
  --ignore-existing \
  --exclude '.cache/' \
  --exclude '.local/share/Trash/' \
  --exclude '.local/share/stack/' \
  --exclude '.m2/repository/' \
  --exclude '.stack/' \
  --exclude 'snap/' \
  --exclude 'VMs/' \
  "$HOME" "$@"
