#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_at_least_2_args "$@"

rsync \
  --archive \
  --itemize-changes \
  --human-readable \
  --executability \
  --progress \
  --stats \
  "$@"
