#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.bash"
check_at_least_2_args "$@"

rsync \
  --archive \
  --itemize-changes \
  --human-readable \
  --executability \
  --partial \
  --progress \
  --atimes \
  --stats \
  --links \
  --ignore-existing \
  "$@"
