#!/usr/bin/env bash

set -euox pipefail

readonly url='https://raw.githubusercontent.com/pauleve/docker-mtgo/master/run-mtgo'
readonly run_mtgo_file="${XDG_DATA_HOME}/docker-mtgo/run-mtgo"

mkdir --parents "$(dirname "${run_mtgo_file}")"
etag-dl "${url}" "${run_mtgo_file}"
chmod +x "${run_mtgo_file}"

# TODO winecfg (--winecfg)
# TODO try sound (--sound)
# TODO Wayland/podman stuff https://github.com/pauleve/docker-mtgo/issues/44

"${run_mtgo_file}" --update --bind "${HOME}/MTG" "$@" > /dev/null 2>&1 &
disown
