#!/usr/bin/env bash

set -euox pipefail

readonly url='https://raw.githubusercontent.com/pauleve/docker-mtgo/master/run-mtgo'
readonly etag_file="${XDG_CACHE_HOME}/docker-mtgo/etag"
readonly run_mtgo_file="${XDG_DATA_HOME}/docker-mtgo/run-mtgo"

mkdir --parents "$(dirname "${etag_file}")"
mkdir --parents "$(dirname "${run_mtgo_file}")"
touch "${etag_file}"
curl --silent  --show-error --location --etag-compare "${etag_file}" --etag-save "${etag_file}" --output "${run_mtgo_file}" "${url}"
chmod +x "${run_mtgo_file}"

# TODO winecfg (--winecfg)
# TODO try sound (--sound)
# TODO Wayland/podman stuff https://github.com/pauleve/docker-mtgo/issues/44

"${run_mtgo_file}" --update --bind "${HOME}/MTG" "$@" > /dev/null 2>&1 &
disown
