#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_most_1_arg "$@"

if [[ "$#" -eq 0 ]]; then
  SCREENSHOT_FILE="${HOME}/screenshot_$(date +%Y%m%d_%H%M%S).png"
  readonly SCREENSHOT_FILE
else
  readonly SCREENSHOT_FILE="$1"
fi

shotgun --geometry "$(hacksaw)" --format 'png' "${SCREENSHOT_FILE}"
log::log "Saved to: ${SCREENSHOT_FILE}"
