#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_most_1_arg "$@"

if [[ "$#" -eq 0 ]]; then
  screenshot_file="${HOME}/screenshot_$(date +%Y%m%d_%H%M%S).png"
  readonly screenshot_file
else
  readonly screenshot_file="$1"
fi

shotgun --geometry "$(hacksaw)" --format 'png' "${screenshot_file}"
log::log "Saved to: ${screenshot_file}"
