#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

# set +u to avoid 'ZSH_VERSION: unbound variable'
set +u

# shellcheck disable=SC1091
source "${SDKMAN_DIR}/bin/sdkman-init.sh"

log 'Pruning SDKMAN packages'
prune_sdkman_packages
log 'Pruning SDKMAN packages'

log 'Pruning Temurin JDKs'
prune_tem_jdks
log 'Pruning Temurin JDKs'

log 'Rewriting .sdkmanrc files'
rewrite_sdkmanrc_file_java_versions
log 'Rewrote .sdkmanrc files'

set -u
