#!/usr/bin/env bash

# @description Update SDKMAN metadata, install/upgrade configured SDKMAN packages and Temurin JDKs, then set the default JDK to the latest installed.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

# Subshell isolates set +u and trap - ERR so parent strict mode is never touched.
# Both are needed: set -u and ERR trap (via -E) are inherited by subshells.
(
  set +u
  trap - ERR

  # shellcheck disable=SC1091 # sdkman-init.sh path is dynamic via SDKMAN_DIR env var
  source "${SDKMAN_DIR}/bin/sdkman-init.sh"

  log::log 'Updating SDKMAN metadata'
  sdkman::update_metadata
  log::log 'Updated SDKMAN metadata'

  log::log 'Updating SDKMAN packages'
  sdkman_packages::install_sdkman_packages
  log::log 'Updated SDKMAN packages'

  log::log 'Updating Temurin JDKs'
  sdkman_jdks::install_latest_tem_jdks
  log::log 'Updated Temurin JDKs'

  log::log 'Setting default JDK'
  sdkman_jdks::set_default_jdk_to_latest_patch_of_current_major
  log::log 'Set default JDK'
)
