#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

# set +u to avoid 'ZSH_VERSION: unbound variable'
set +u

# shellcheck disable=SC1091
source "${SDKMAN_DIR}/bin/sdkman-init.sh"

log::log 'Updating SDKMAN metadata'
sdkman::update_metadata
log::log 'Updated SDKMAN metadata'

log::log 'Updating SDKMAN packages'
sdkman_packages::install_sdkman_packages
log::log 'Updated SDKMAN packages'

log::log 'Updating Temurin JDKs'
sdkman_jdks::install_latest_tem_jdks
log::log 'Updated Temurin JDKs'

log::log 'Setting default JDK'
sdkman_jdks::set_default_jdk_to_latest_installed
log::log 'Set default JDK'

set -u
