#!/usr/bin/env bash

# @description Print the shrug emoticon `¯\_(ツ)_/¯` to stdout (no trailing newline).
# @noargs
# @stdout The shrug emoticon.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

printf '%s' '¯\_(ツ)_/¯'
