#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_exactly_2_args "$@"

if files::exists "$1" && files::exists "$2" || dirs::exists "$1" && dirs::exists "$2"; then
  temp_file="$(mktemp)" || exit 1
  trap 'rm --force -- "${temp_file}"' EXIT
  mv -- "$1" "${temp_file}"
  mv -- "$2" "$1"
  mv -- "${temp_file}" "$2"
  log::log "$1 <-> $2"
else
  if [[ -e "$1" && -e "$2" ]]; then
    log::die "Cannot swap file and directory"
  fi
  if [[ ! -e "$1" ]]; then
    log::die "$1 does not exist"
  fi
  if [[ ! -e "$2" ]]; then
    log::die "$2 does not exist"
  fi
fi
