#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_exactly_2_args "$@"

if file_exists "$1" && file_exists "$2" || dir_exists "$1" && dir_exists "$2"; then
  readonly temp_file="swap.tmp"
  mv -- "$1" "${temp_file}"
  mv -- "$2" "$1"
  mv -- "${temp_file}" "$2"
  log "$1 <-> $2"
else
  if [[ -e "$1" && -e "$2" ]]; then
    die "Cannot swap file and directory"
  fi
  if [[ ! -e "$1" ]]; then
    die "$1 does not exist"
  fi
  if [[ ! -e "$2" ]]; then
    die "$2 does not exist"
  fi
fi
