#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_exactly_2_args "$@"

if [[ -f "$1" && -f "$2" ]] || [[ -d "$1" && -d "$2" ]]; then
  readonly temp_file="swap.tmp"
  mv -- "$1" "${temp_file}"
  mv -- "$2" "$1"
  mv -- "${temp_file}" "$2"
  log "$1 <-> $2"
else
  if [[ -e "$1" && -e "$2" ]]; then
    log "Cannot swap file and directory"
  fi
  if [[ ! -e "$1" ]]; then
    log "$1 does not exist"
  fi
  if [[ ! -e "$2" ]]; then
    log "$2 does not exist"
  fi
  exit 2
fi
