#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

if ! commands::executable_exists 'appman'; then
  log::die 'appman executable not found'
fi

mapfile -t appimages_from_package_list < <(packages::get_universal 'appimage' "$@" | sort)
readonly appimages_from_package_list

mapfile -t appimages_installed < <(
  find "${XDG_DATA_HOME}/appman/" \
    -mindepth 1 -maxdepth 1 -type 'd' ! -name 'appman' -printf '%f\n' \
    | sort
)
readonly appimages_installed

mapfile -t appimages_to_install < <(
  comm -23 \
    <(arrays::to_lines "${appimages_from_package_list[@]}") \
    <(arrays::to_lines "${appimages_installed[@]}")
)
readonly appimages_to_install

mapfile -t appimages_to_remove < <(
  comm -13 \
    <(arrays::to_lines "${appimages_from_package_list[@]}") \
    <(arrays::to_lines "${appimages_installed[@]}")
)
readonly appimages_to_remove

if (("${#appimages_to_install[@]}")) && prompt::yn 'Install missing AppImage packages?'; then
  log::log 'Installing missing AppImage packages'
  arrays::to_lines "${appimages_to_install[@]}" | xargs --no-run-if-empty --max-args=1 appman install
  log::log 'Installed missing AppImage packages'
fi

for appimage_to_remove in "${appimages_to_remove[@]}"; do
  if prompt::yn "Remove ${appimage_to_remove}?"; then
    log::log "Removing ${appimage_to_remove}"
    # I don't know why remove operation exit code is non-zero
    appman -R "${appimage_to_remove}" || true
    log::log "Removed ${appimage_to_remove}"
  fi
done

log::log 'Updating all AppImage packages'
appman update
log::log 'Updated all AppImage packages'
