#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if commands::executable_exists 'flatpak'; then
  sync-flatpaks
fi

if commands::executable_exists 'appman'; then
  sync-appimages
fi

if commands::executable_exists 'home-manager'; then
  home-manager-update
fi
