#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
# pass-through: any arg count valid ($@ forwarded as filter args to packages::get_universal)

commands::assert_executable_exists 'flatpak'

mapfile -t flatpaks_from_package_list < <(packages::get_universal 'flatpak' "$@" | sort)
readonly flatpaks_from_package_list

mapfile -t flatpaks_installed < <(flatpak list --user --app --columns application | sort)
readonly flatpaks_installed

mapfile -t flatpaks_to_install < <(arrays::diff flatpaks_from_package_list flatpaks_installed)
readonly flatpaks_to_install

mapfile -t flatpaks_to_remove < <(
  comm -13 \
    <(arrays::to_lines "${flatpaks_from_package_list[@]}") \
    <(arrays::to_lines "${flatpaks_installed[@]}")
)
readonly flatpaks_to_remove

if (("${#flatpaks_to_install[@]}")) && prompt::yn 'Install missing Flatpak packages?'; then
  log::log 'Installing missing Flatpak packages'
  arrays::to_lines "${flatpaks_to_install[@]}" | xargs --no-run-if-empty --max-args=100 flatpak install --user --noninteractive
  log::log 'Installed missing Flatpak packages'
fi

for flatpak_to_remove in "${flatpaks_to_remove[@]}"; do
  flatpak_name="$(
    flatpak list --user --app --columns name --columns application \
      | awk --field-separator $'\t' --assign "to_remove=${flatpak_to_remove}" '$2 == to_remove { print $1 }'
  )"
  if prompt::yn "Remove ${flatpak_name} (${flatpak_to_remove})?"; then
    log::log "Removing ${flatpak_name} (${flatpak_to_remove})"
    flatpak remove --user --noninteractive "${flatpak_to_remove}"
    log::log "Removed ${flatpak_name} (${flatpak_to_remove})"
  fi
done

log::log 'Removing unused Flatpak runtimes'
flatpak uninstall --user --noninteractive --unused
log::log 'Removed unused Flatpak runtimes'

log::log 'Updating all Flatpak packages'
flatpak update --user --noninteractive
log::log 'Updated all Flatpak packages'

if flatpak list --user --app | grep::contains_word_ignore_case 'com.google.chrome'; then
  flatpak override --user \
    --filesystem="${XDG_DATA_HOME}/applications:create" \
    --filesystem="${XDG_DATA_HOME}/icons:create" \
    'com.google.Chrome'
fi
