#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_no_args "$@"

systemctl status '*timer' --no-pager
systemctl status --user '*timer' --no-pager
