#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

systemctl status '*timer' --no-pager
systemctl status --user '*timer' --no-pager
