#!/usr/bin/env bash

# @description Set the active Tailscale exit node to the given node.
# @arg $1 node Tailscale node name or IP to route exit traffic through.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_exactly_1_arg "$@"

tailscale set --exit-node="$1"
