#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_at_least_1_arg "$@"

for file in "$@"; do
  if [[ -e "${file}" ]] && ! file_exists "${file}"; then
    log "${file} is NOT a file"
  else
    touch "${file}"
    chmod +x "${file}"
  fi
done
