#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.bash"
check_at_least_1_arg "$@"

for file; do
  if [[ -e "${file}" && ! -f "${file}" ]]; then
    log "${file} is NOT a file"
  else
    touch "${file}"
    chmod +x "${file}"
  fi
done
