#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"

if stdin_exists; then
  check_no_args "$@"
  awk '{$1=$1};1'
else
  check_exactly_1_arg "$@"
  awk '{$1=$1};1' "$1"
fi
