#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0

if args::stdin_exists; then
  args::check_no_args "$@"
  awk '{$1=$1};1'
else
  args::check_exactly_1_arg "$@"
  awk '{$1=$1};1' "$1"
fi
