#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_at_most_1_arg "$@"
if [[ "$#" -eq 0 ]]; then
  check_for_stdin
fi

if [[ "$#" -eq 0 ]]; then
  awk '{$1=$1};1'
else
  awk '{$1=$1};1' "$1"
fi
