#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

find '/usr/share/zoneinfo/' -type 'f' -print0 \
  | xargs --null md5sum \
  | grep "$(md5sum '/etc/localtime' | cut --delimiter=' ' --fields='1')" \
  | sed 's|.*/zoneinfo/||'
