#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_at_least_1_arg "$@"

for archive in "$@"; do
  if [ -f "${archive}" ]; then
    case "${archive}" in
      *.tar.bz2) tar --extract --verbose --bzip2 --file "${archive}" ;;
      *.tar.gz) tar --extract --verbose --gzip --file "${archive}" ;;
      *.tar.xz) tar --extract --verbose --xz --file "${archive}" ;;
      *.tar.zst) tar --extract --verbose --use-compress-program=unzstd --file "${archive}" ;;
      *.bz2) bzip2 --decompress --verbose "${archive}" ;;
      *.exe) cabextract "${archive}" ;;
      *.gz) gzip --decompress --verbose "${archive}" ;;
      *.lzma) xz --decompress --verbose --format=lzma "${archive}" ;;
      *.rar) rar x "${archive}" ;;
      *.tar) tar --extract --verbose --file "${archive}" ;;
      *.tbz2) tar --extract --verbose --bzip2 --file ;;
      *.tgz) tar --extract --verbose --gzip --file "${archive}" ;;
      *.xz) xz --decompress --verbose "${archive}" ;;
      *.zip) unzip "${archive}" ;;
      *.7z) 7z x "${archive}" ;;
      *) die "Don't know how to extract '${archive}'" ;;
    esac
    log "extracted '${archive}'"
  else
    die "'${archive}' is not a regular file"
  fi
done
