#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0

if stdin_exists; then
  check_no_args "$@"
  awk '!x[$0]++'
else
  check_exactly_1_arg "$@"
  awk '!x[$0]++' "$1"
fi
