#!/usr/bin/env bash

# @description Refresh the fwupd metadata cache and apply pending firmware updates via `fwupdmgr`.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

log::log 'Updating firmware'
sudo fwupdmgr refresh --force
sudo fwupdmgr update --offline --assume-yes
log::log 'Updated firmware'
