#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_no_args "$@"

sudo pacman-mirrors --country 'United_States,Canada'
sudo pacman-mirrors --fasttrack
sudo pacman --sync --refresh --refresh --sysupgrade
