#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.bash"
check_no_args "$@"

log 'Updating AWS CLI'
readonly aws_cli_url='https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip'
readonly aws_cli_cache_dir="${XDG_CACHE_HOME}/aws/cli"
readonly aws_cli_etag_file="${aws_cli_cache_dir}/etag"
readonly aws_cli_zip_file="${aws_cli_cache_dir}/aws-cli-v2.zip"
readonly aws_cli_extract_dir="${aws_cli_cache_dir}/extracted"
rm -rf "${aws_cli_zip_file}" "${aws_cli_extract_dir}"
mkdir --parents "${aws_cli_cache_dir}"
touch "${aws_cli_etag_file}"
curl --silent --show-error --location --etag-compare "${aws_cli_etag_file}" --etag-save "${aws_cli_etag_file}" --output "${aws_cli_zip_file}" "${aws_cli_url}"
if [[ -f "${aws_cli_zip_file}" ]]; then
  unzip -q "${aws_cli_zip_file}" -d "${aws_cli_extract_dir}"
  sudo "${aws_cli_extract_dir}/aws/install" --bin-dir '/usr/local/bin' --install-dir '/usr/local/aws-cli' --update
fi
log 'Updated AWS CLI'
