#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

log 'Updating firmware'
sudo fwupdmgr refresh --force
sudo fwupdmgr update --offline --assume-yes
log 'Updated firmware'
