#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

for repo in 'crypt' 'packages' 'scripts'; do
  log::log "Executing git pull for: ${repo}"
  repo_dir="${PERSONAL_PROJECTS_DIR}/${repo}"
  git -C "${repo_dir}" pull
done
