#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.sh"
check_no_args "$@"

sudo pacman-mirrors --country 'United_States,Canada'
sudo pacman-mirrors --fasttrack
sudo pacman -Syyu
