#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0

if stdin_exists; then
  check_no_args "$@"
  tr '[:lower:]' '[:upper:]'
else
  check_at_least_1_arg "$@"
  for file in "$@"; do
    dirname="$(dirname -- "${file}")" || exit 1
    readonly dirname
    filename="$(basename -- "${file}")" || exit 1
    readonly filename
    lower_filename="$(printf '%s\n' "${filename}" | tr '[:lower:]' '[:upper:]')" || exit 1
    readonly lower_filename
    target_file="${dirname}/${lower_filename}"
    readonly target_file
    if [[ "${lower_filename}" != "${filename}" ]]; then
      mv -- "${file}" "${target_file}"
      log "${file} -> ${target_file}"
    else
      log "${file} not renamed"
    fi
  done
fi
