#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"

if stdin_exists; then
  check_no_args "$@"
  tr '[:lower:]' '[:upper:]'
else
  check_at_least_1_arg "$@"
  for file; do
    dirname="$(dirname -- "${file}")" || exit 1
    filename="$(basename -- "${file}")" || exit 1
    lower_filename="$(echo "${filename}" | tr '[:lower:]' '[:upper:]')" || exit 1
    target_file="${dirname}/${lower_filename}"
    if [[ "${lower_filename}" != "${filename}" ]]; then
      mv -- "${file}" "${target_file}"
      log "${file} -> ${target_file}"
    else
      log "${file} not renamed"
    fi
  done
fi
