#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_exactly_1_arg "$@"

jq --null-input --raw-output --arg v "$1" '$v|@uri'
