#!/usr/bin/env bash

# @description Print the URI-encoded form of the given string (via `jq`'s `@uri` filter).
# @arg $1 value String to URI-encode.
# @stdout The URI-encoded value.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_exactly_1_arg "$@"

jq --null-input --raw-output --arg v "$1" '$v|@uri'
