#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_exactly_1_arg "$@"

jq --null-input --raw-output --arg v "$1" '$v|@uri'
