#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

wrappers::curl --ipv4 --write-out '\n' 'ifconfig.me/ip'
wrappers::curl --ipv6 --write-out '\n' 'ifconfig.me/ip'
