#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_no_args "$@"

curl_wrapper --ipv4 --write-out '\n' 'ifconfig.me/ip'
curl_wrapper --ipv6 --write-out '\n' 'ifconfig.me/ip'
