#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"

# SP  ' '  0x20 = · U+00B7 Middle Dot
# TAB '\t' 0x09 = ￫ U+FFEB Halfwidth Rightwards Arrow
# CR  '\r' 0x0D = § U+00A7 Section Sign (⏎ U+23CE also works fine)
# LF  '\n' 0x0A = ¶ U+00B6 Pilcrow Sign (was "Paragraph Sign")
if stdin_exists; then
  check_no_args "$@"
  sed 's/ /·/g;s/\t/￫/g;s/\r/§/g;s/$/¶/g'
else
  check_exactly_1_arg "$@"
  sed 's/ /·/g;s/\t/￫/g;s/\r/§/g;s/$/¶/g' "$1"
fi
