#!/usr/bin/env bash

# @description Print the password for the currently connected Wi-Fi network via `nmcli device wifi show-password`.
# @noargs
# @stdout The nmcli show-password block (SSID, password, QR code).

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

nmcli device 'wifi' 'show-password'
