#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_at_most_1_arg "$@"

if [[ "$#" -eq 0 ]]; then
  dir="${XDG_CONFIG_HOME}/home-manager"
else
  dir="$1"
fi
readonly dir
mkdir --parents "${dir}"

readonly pkgs_file="${CODE_DIR}/Personal/packages/nixpkgs.csv"
awk -F',' '$3 == "y" && $7 == "" { print $2 }' "${pkgs_file}" > "${dir}/personal-desktop.pkgs"
awk -F',' '$4 == "y" && $7 == "" { print $2 }' "${pkgs_file}" > "${dir}/personal-laptop.pkgs"
awk -F',' '$5 == "y" && $7 == "" { print $2 }' "${pkgs_file}" > "${dir}/work-laptop.pkgs"
awk -F',' '$6 == "y" && $7 == "" { print $2 }' "${pkgs_file}" > "${dir}/server.pkgs"
