#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

readonly compose_file='./compose.yaml'

if file_exists "${compose_file}"; then
  die "${compose_file} exists"
fi

# shellcheck disable=SC2016
echo -n 'services:
  some_service:
    image: some_image:latest
    container_name: some_name
    hostname: some_hostname
    restart: unless-stopped
    ports:
      - ${TAILNET_IP:?}:80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: ${PUID:?}
      PGID: ${PGID:?}
      TZ: Etc/UTC
' > "${compose_file}"
