#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_no_args "$@"

if is_personal && is_desktop; then
  readonly package_list_column=3
elif is_personal && is_laptop; then
  readonly package_list_column=4
elif is_work && is_laptop; then
  readonly package_list_column=5
elif is_headless; then
  readonly package_list_column=6
else
  die "Could not determine which computer this is"
fi

mkdir --parents "$(dirname "${HOME_MANAGER_PACKAGES_FILE}")"
(
  echo "{ pkgs, ... }:"
  echo ""
  echo "{"
  echo "  home.packages = ["
  dl "${NIXPKGS_PACKAGES_URL}" | awk -F',' "\$${package_list_column} == \"y\" && \$7 == \"\" { print \"    pkgs.\" \$2 }"
  echo "  ];"
  echo "}"
) > "${HOME_MANAGER_PACKAGES_FILE}"
