#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_no_args "$@"

if is_personal && is_desktop; then
  col_num=3
elif is_personal && is_laptop; then
  col_num=4
elif is_work && is_latop; then
  col_num=5
elif is_headless; then
  col_num=6
else
  die "Could not determine which computer this is"
fi
readonly col_num
readonly pkgs_file="${PACKAGES_DIR}/nixpkgs.csv"

mkdir --parents "${HOME_MANAGER_DIR}"
dl "${NIXPKGS_PACKAGES_URL}" | awk -F',' "\$${col_num} == \"y\" && \$7 == \"\" { print \$2 }" > "${HOME_MANAGER_DIR}/packages"
