#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../lib/functions.bash"
check_at_most_1_arg "$@"

if [[ "$#" -eq 0 ]]; then
  curl "wttr.in/${WTTR_CITY}"
else
  curl "wttr.in/$1"
fi
