#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_at_most_1_arg "$@"

if [[ "$#" -eq 0 ]]; then
  readonly city="${WTTR_CITY}"
else
  readonly city="$1"
fi
downloads::download_and_cat "wttr.in/${city}"
