#!/usr/bin/env bash

# @description Convert YAML to JSON. Reads from stdin or from the given file.
# @arg $1 file Optional YAML file path. When omitted, reads from stdin instead.
# @stdout JSON equivalent of the YAML input.
# @exitcode 0 success
# @exitcode 1 yq missing, or invalid YAML input

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
commands::assert_executable_exists 'yq'

if args::stdin_exists; then
  args::check_no_args "$@"
  yaml::to_json
else
  args::check_exactly_1_arg "$@"
  readonly FILE="$1"
  yaml::to_json "${FILE}"
fi
