#!/usr/bin/env bash

# @description Switch prime-select to integrated Intel graphics on work hosts.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

if ! hosts::is_work; then
  exit 0
fi
current_selection="$(prime-select query)"
readonly current_selection
if [[ "${current_selection}" == 'intel' ]]; then
  exit 0
fi
if ! prompt::yn 'Use integrated graphics?'; then
  exit 0
fi

log::log 'Selecting integrated graphics'
sudo prime-select 'intel'
log::log 'Selected integrated graphics'
