#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.sh"
check_no_args "$@"

if ! executable_exists 'flatpak'; then
  log 'flatpak executable not found'
  exit 0
fi
if flatpak remotes --columns=title | contains_word 'Flathub'; then
  exit 0
fi
if ! prompt_yn 'Add Flathub flatpak repo?'; then
  exit 0
fi

log 'Adding Flathub flatpak repo'
flatpak remote-add --if-not-exists 'flathub' 'https://flathub.org/repo/flathub.flatpakrepo'
log 'Added Flathub flatpak repo'
