#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_no_args "$@"

if ! executable_exists 'fail2ban-server'; then
  log 'fail2ban-server executable not found'
  exit 0
fi

readonly src_file="${HOME}/.etc/fail2ban-sshd.local"
readonly dest_file='/etc/fail2ban/jail.d/sshd.local'

orig_hash="$(file_hash "${dest_file}")" || exit 1
readonly orig_hash
root_copy_file "${src_file}" "${dest_file}"
cur_hash="$(file_hash "${dest_file}")" || exit 1
readonly cur_hash

if [[ "${orig_hash}" != "${cur_hash}" ]]; then
  restart_system_service_if_enabled 'fail2ban.service'
fi
