#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! executable_exists 'fail2ban-client'; then
  exit 0
fi

enable_system_service_unit 'fail2ban.service'
