#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

if is_server; then
  exit 0
fi

readonly src_file="${HOME}/.etc/sysctl-max-user-watches.conf"
readonly dest_file='/etc/sysctl.d/max-user-watches.conf'

# Copy instead of symlink - see 'protected_symlinks' in https://www.kernel.org/doc/Documentation/sysctl/fs.txt
copy_system_file "${src_file}" "${dest_file}"

reload_sysctl_conf
