#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.sh"
check_no_args "$@"

readonly target_file="${HOME}/.etc/sysctl-max_user_watches.conf"
readonly link_file='/etc/sysctl.d/50-max_user_watches.conf'

link_file "${target_file}" "${link_file}"
