#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/../lib/functions.sh"
check_no_args "$@"

readonly target_file="${HOME}/.etc/sysctl-kvals.conf"
readonly link_file='/etc/sysctl.d/90-kvals.conf'

link_file "${target_file}" "${link_file}"
