#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

readonly service_desc='ClamAV daemon'
readonly service_unit='clamav-daemon.service'

enable_system_service "${service_desc}" "${service_unit}"
