#!/usr/bin/env bash

# @description Migrate the default ~/.bash_history file to the path specified by HISTFILE when one exists.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

if strings::is_empty "${HISTFILE:-}"; then
  exit 0
fi

readonly old_history_file="${HOME}/.bash_history"
readonly new_history_file="${HISTFILE}"

if ! files::exists "${old_history_file}"; then
  exit 0
fi

files::move "${old_history_file}" "${new_history_file}"
