#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if [[ -z "${HISTFILE:-}" ]]; then
  exit 0
fi

readonly old_history_file="${HOME}/.bash_history"
readonly new_history_file="${HISTFILE}"

if [[ ! -f "${old_history_file}" ]]; then
  exit 0
fi

move_file "${old_history_file}" "${new_history_file}"
