#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

readonly service_desc='Trash cleanup'
readonly service_unit='trash-cleanup.timer'
readonly required_executable='delete-from-trash'
readonly system_or_user='user'

enable_service "${service_desc}" "${service_unit}" "${required_executable}" "${system_or_user}"
