#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if executable_exists 'trash-empty'; then
  enable_user_service_unit 'trash-empty.timer'
fi
