#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! os::is_arch && ! os::is_cachyos; then
  exit 0
fi

if ! commands::executable_exists 'reflector'; then
  log::log 'reflector executable not found'
  exit 0
fi

readonly src_file="${HOME}/.etc/reflector.conf"
readonly dest_file='/etc/xdg/reflector/reflector.conf'

orig_hash="$(files::hash "${dest_file}")"
readonly orig_hash
files::root_copy "${src_file}" "${dest_file}"
cur_hash="$(files::hash "${dest_file}")"
readonly cur_hash

if [[ "${orig_hash}" != "${cur_hash}" ]]; then
  systemctl::restart_system_service_if_enabled 'reflector.service'
fi
