#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! is_arch && ! is_endeavour; then
  exit 0
fi

if ! executable_exists 'reflector'; then
  log 'reflector executable not found'
  exit 0
fi

readonly src_file="${HOME}/.etc/reflector.conf"
readonly dest_file='/etc/xdg/reflector/reflector.conf'

orig_hash="$(file_hash "${dest_file}")"
readonly orig_hash
root_copy_file "${src_file}" "${dest_file}"
cur_hash="$(file_hash "${dest_file}")"
readonly cur_hash

if [[ "${orig_hash}" != "${cur_hash}" ]]; then
  restart_system_service_if_enabled 'reflector.service'
fi
