#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if ! is_arch && ! is_endeavour; then
  exit 0
fi

if ! executable_exists 'reflector'; then
  log 'reflector executable not found'
  exit 0
fi

readonly src_file="${HOME}/.etc/reflector.conf"
readonly dest_file='/etc/xdg/reflector/reflector.conf'
root_copy_file "${src_file}" "${dest_file}"

restart_system_service_if_enabled 'reflector.service'
