#!/usr/bin/env bash

# @description Enable the reflector.timer system unit when reflector is installed.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

if ! commands::executable_exists 'reflector'; then
  exit 0
fi

systemctl::enable_system_service_unit 'reflector.timer'
