#!/usr/bin/env bash

# @description Enable the pkgfile-update.timer system unit when pkgfile is installed.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

if ! commands::executable_exists 'pkgfile'; then
  exit 0
fi

systemctl::enable_system_service_unit 'pkgfile-update.timer'
