#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

readonly src_file="${HOME}/.etc/sudo-disable-admin-flag"
readonly dest_file='/etc/sudoers.d/disable-admin-flag'
root_copy_file "${src_file}" "${dest_file}"
