#!/usr/bin/env bash

# @description Install the sudoers.d drop-in that disables the sudo admin flag file.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

readonly src_file="${HOME}/.etc/sudo-disable-admin-flag"
readonly dest_file='/etc/sudoers.d/disable-admin-flag'
files::root_copy "${src_file}" "${dest_file}"
