#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

readonly src_file="${HOME}/.etc/sudo-timestamp-timeout"
readonly dest_file='/etc/sudoers.d/timestamp-timeout'
root_copy_file "${src_file}" "${dest_file}"
