#!/usr/bin/env bash

# @description Install the sudoers.d drop-in that sets the sudo credential timestamp timeout.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

readonly src_file="${HOME}/.etc/sudo-timestamp-timeout"
readonly dest_file='/etc/sudoers.d/timestamp-timeout'
files::root_copy "${src_file}" "${dest_file}"
