#!/usr/bin/env bash

# @description Interactively delete the ~/.sudo_as_admin_successful marker file if present.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

readonly sudo_as_admin_file="${HOME}/.sudo_as_admin_successful"

if ! files::exists "${sudo_as_admin_file}"; then
  exit 0
fi
if ! prompt::yn "Delete ${sudo_as_admin_file}?"; then
  exit 0
fi

log::log "Removing: ${sudo_as_admin_file}"
rm -- "${sudo_as_admin_file}"
log::log "Removed: ${sudo_as_admin_file}"
