#!/usr/bin/env bash

# @description Strip the sudo_as_admin_successful hint block from /etc/bash.bashrc, backing the file up first.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

readonly bashrc_file='/etc/bash.bashrc'

if ! files::exists "${bashrc_file}"; then
  exit 0
fi

if ! grep::file_contains_regex "${bashrc_file}" 'if.*\.sudo_as_admin_successful'; then
  exit 0
fi

log::log "Removing sudo hint block from: ${bashrc_file}"

sudo cp "${bashrc_file}" "${bashrc_file}.$(date +%Y%m%d_%H%M%S).bak"

# shellcheck disable=SC2016 # awk script body uses $0/$N field refs that are not shell expansions
files::root_transform "${bashrc_file}" awk '
BEGIN { delete_next = 0; in_block = 0; buffer_line = ""; has_buffer = 0 }
{
    # Check if we are entering the sudo_as_admin_successful block
    if ($0 ~ /if.*\.sudo_as_admin_successful/) {
        in_block = 1
        has_buffer = 0  # Don'\''t print the buffered comment line
        next
    }

    # If we are in the block, skip lines until we find the closing fi
    if (in_block) {
        if ($0 ~ /^fi$/) {
            in_block = 0
        }
        next
    }

    # If we have a buffered line, print it before processing current line
    if (has_buffer) {
        print buffer_line
    }

    # If current line is a comment, buffer it (in case next line is the if statement)
    if ($0 ~ /^[[:space:]]*#/) {
        buffer_line = $0
        has_buffer = 1
    } else {
        # Not a comment, print it immediately
        print $0
        has_buffer = 0
    }
}
END {
    # Print any remaining buffered line
    if (has_buffer) {
        print buffer_line
    }
}
'

log::log "Removed sudo hint block from: ${bashrc_file}"
