#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

user_groups="$(groups "${USER}")"
readonly user_groups

all_groups="$(getent group | cut --delimiter=':' --fields='1')"
readonly all_groups

readonly groups=('docker' 'kvm' 'input' 'libvirt' 'sudo' 'sys' 'wheel')

for group in "${groups[@]}"; do
  if ! contains_word "${group}" <<< "${all_groups}"; then
    continue
  fi
  if contains_word "${group}" <<< "${user_groups}"; then
    continue
  fi
  if ! prompt_yn "Add ${USER} to group: ${group}?"; then
    continue
  fi
  log "Adding user to group: ${group}"
  sudo usermod --append --groups "${group}" "${USER}"
  log "Added user to group: ${group}"
done
