#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! is_fedora; then
  exit 0
fi

if ! executable_exists 'dnf'; then
  log 'dnf executable not found'
  exit 0
fi

if ! prompt_yn 'Add RPM Fusion repos?'; then
  exit 0
fi

for repo in 'rpmfusion-free-release' 'rpmfusion-nonfree-release'; do
  if ! dnf list --installed "${repo}" > '/dev/null' 2>&1 && prompt_yn "Add ${repo} repository?"; then
    if [[ "${repo}" == 'rpmfusion-free-release' ]]; then
      sudo dnf install "https://mirrors.rpmfusion.org/free/fedora/${repo}-$(rpm --eval='%fedora').noarch.rpm"
    else
      sudo dnf install "https://mirrors.rpmfusion.org/nonfree/fedora/${repo}-$(rpm --eval='%fedora').noarch.rpm"
    fi
  fi
done
