#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_no_args "$@"

if ! is_fedora; then
  exit 0
fi
if ! executable_exists 'dnf'; then
  log 'dnf executable not found'
  exit 0
fi

readonly src_file="${HOME}/.etc/dnf.conf"
readonly dest_file='/etc/dnf/dnf.conf'
root_copy_file "${src_file}" "${dest_file}"
