#!/usr/bin/env bash

# @description Copy the user's dnf.conf into /etc/dnf/dnf.conf on Fedora hosts.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

if ! os::is_fedora; then
  exit 0
fi
if ! commands::executable_exists 'dnf'; then
  log::log 'dnf executable not found'
  exit 0
fi

readonly src_file="${HOME}/.etc/dnf.conf"
readonly dest_file='/etc/dnf/dnf.conf'
files::root_copy "${src_file}" "${dest_file}"
