#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if localectl | contains_exactly 'LANG=en_US.UTF-8'; then
  exit 0
fi
if ! prompt_yn 'Set locale to en_US.UTF8?'; then
  exit 0
fi

log 'Setting locale to en_US.UTF-8'
if ! file_contains_regex '^en_US.UTF-8 UTF-8' '/etc/locale.gen'; then
  echo 'en_US.UTF-8 UTF-8' | sudo tee --append '/etc/locale.gen' > '/dev/null'
fi
sudo locale-gen
sudo localectl set-locale 'LANG=en_US.UTF-8'
log 'Set locale to en_US.UTF-8'
