#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! executable_exists 'ufw'; then
  log 'ufw executable not found'
  exit 0
fi

if ! sudo ufw status verbose | contains_word_ignore_case 'deny (incoming)'; then
  if prompt_yn 'Set UFW to deny incoming?'; then
    sudo ufw default deny 'incoming'
  fi
fi

if ! grep --perl-regexp --quiet --ignore-case 'anywhere on tailscale0\s+allow in\s+anywhere' <<< "$(sudo ufw status verbose)"; then
  if prompt_yn "Set UFW to allow all incoming traffic from tailnet?"; then
    sudo ufw allow in on 'tailscale0'
  fi
fi

if ! grep --perl-regexp --quiet --ignore-case '22/tcp0\s+allow in\s+anywhere' <<< "$(sudo ufw status verbose)"; then
  if prompt_yn "Set UFW to allow all incoming traffic on port 22 (ssh)?"; then
    sudo ufw allow ssh
  fi
fi

if ! sudo ufw status verbose | contains_word_ignore_case 'allow (outgoing)'; then
  if prompt_yn 'Set UFW to allow outgoing?'; then
    sudo ufw default allow 'outgoing'
  fi
fi

if ! sudo ufw status verbose | contains_word_ignore_case 'status: active'; then
  if prompt_yn 'Enable UFW?'; then
    sudo ufw --force enable
  fi
fi
