#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! executable_exists 'ufw'; then
  log 'ufw executable not found'
  exit 0
fi

if ! sudo ufw status verbose | contains_word_ignore_case 'deny (incoming)'; then
  if prompt_yn 'Set UFW to deny incoming?'; then
    sudo ufw default deny 'incoming'
  fi
fi

if ! sudo ufw status verbose | contains_perl_regex_ignore_case 'anywhere on tailscale0\s+allow in\s+anywhere'; then
  if prompt_yn 'Set UFW to allow incoming traffic from tailnet?'; then
    sudo ufw allow in on 'tailscale0'
  fi
fi

if ! sudo ufw status verbose | contains_perl_regex_ignore_case '22/tcp\s+allow in\s+anywhere'; then
  if prompt_ny 'Set UFW to allow incoming traffic on port 22 (ssh)?'; then
    sudo ufw allow ssh
  fi
fi

if ! sudo ufw status verbose | contains_perl_regex_ignore_case 'anywhere on tailscale0\s+allow in\s+anywhere'; then
  if prompt_yn 'Set UFW to allow incoming traffic from tailnet?'; then
    sudo ufw allow in on 'tailscale0'
  fi
fi

if ! sudo ufw status verbose | contains_perl_regex_ignore_case '22/tcp\s+allow in\s+172\.17\.0\.0/16'; then
  if prompt_ny 'Set UFW to allow incoming traffic on port 22 (ssh) from 172.17.0.0/16 (docker0)?'; then
    sudo ufw allow from '172.17.0.0/16' to any port '22' proto 'tcp'
  fi
fi

if ! sudo ufw status verbose | contains_perl_regex_ignore_case '22/tcp\s+allow in\s+172\.18\.0\.0/16'; then
  if prompt_ny 'Set UFW to allow incoming traffic on port 22 (ssh) from 172.18.0.0/16 (docker_gwbridge)?'; then
    sudo ufw allow from '172.18.0.0/16' to any port '22' proto 'tcp'
  fi
fi

if ! sudo ufw status verbose | contains_perl_regex_ignore_case '45876/tcp\s+allow in\s+172\.17\.0\.0/16'; then
  if prompt_ny 'Set UFW to allow incoming traffic on port 45876 (beszel) from 172.17.0.0/16 (docker0)?'; then
    sudo ufw allow from '172.17.0.0/16' to any port '45876' proto 'tcp'
  fi
fi

if ! sudo ufw status verbose | contains_perl_regex_ignore_case '45876/tcp\s+allow in\s+172\.18\.0\.0/16'; then
  if prompt_ny 'Set UFW to allow incoming traffic on port 45876 (beszel) from 172.18.0.0/16 (docker_gwbridge)?'; then
    sudo ufw allow from '172.18.0.0/16' to any port '45876' proto 'tcp'
  fi
fi

if ! sudo ufw status verbose | contains_word_ignore_case 'allow (outgoing)'; then
  if prompt_yn 'Set UFW to allow outgoing?'; then
    sudo ufw default allow 'outgoing'
  fi
fi

if ! sudo ufw status verbose | contains_word_ignore_case 'status: active'; then
  if prompt_yn 'Enable UFW?'; then
    sudo ufw --force enable
  fi
fi
