#!/usr/bin/env bash

# @description Enable the ufw.service systemd system unit when the ufw binary is installed.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! commands::executable_exists 'ufw'; then
  exit 0
fi

systemctl::enable_system_service_unit 'ufw.service'
