#!/usr/bin/env bash

# @description Run xdg-ninja from its upstream flake via `nix run`, forwarding any arguments through.
# @arg $@ args Arguments forwarded to the upstream xdg-ninja binary.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"

nix run 'github:b3nj5m1n/xdg-ninja' -- "$@"
