#!/usr/bin/env bash

# @description Launch the Zed flatpak (id: dev.zed.Zed) attached to the terminal, forwarding all args.
# @arg $@ args Arguments forwarded verbatim to the flatpak app.
# @exitcode 1 flatpak application is not installed

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
# pass-through: any arg count valid (forwarded to flatpak app)

flatpak::exec_gui 'dev.zed.Zed' "$@"
