#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_no_args "$@"

if ! is_arch && ! is_cachyos; then
  exit 0
fi
if ! executable_exists 'pacman'; then
  log 'pacman executable not found'
  exit 0
fi

readonly src_file="${HOME}/.etc/pacman.conf"
readonly dest_file='/etc/pacman.conf'
root_copy_file "${src_file}" "${dest_file}"
