#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_no_args "$@"

if ! is_arch && ! is_cachyos; then
  exit 0
fi
if ! executable_exists 'pacman'; then
  log 'pacman executable not found'
  exit 0
fi

readonly hooks_dir="/etc/pacman.d/hooks"
for hook_file in "${HOME}/.etc/pacman-"*".hook"; do
  hook_file_name="$(basename "${hook_file}")" || exit 1
  root_copy_file "${hook_file}" "${hooks_dir}/${hook_file_name:7}"
done
