#!/usr/bin/env bash

# @description Install user-maintained pacman hook files into /etc/pacman.d/hooks on Arch/CachyOS hosts.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! os::is_arch && ! os::is_cachyos; then
  exit 0
fi
if ! commands::executable_exists 'pacman'; then
  log::log 'pacman executable not found'
  exit 0
fi

readonly hooks_dir='/etc/pacman.d/hooks'
for hook_file in "${HOME}/.etc/pacman-"*".hook"; do
  hook_file_name="$(basename "${hook_file}")"
  files::root_copy "${hook_file}" "${hooks_dir}/${hook_file_name:7}"
done
