#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! os::is_arch && ! os::is_cachyos; then
  exit 0
fi
if ! commands::executable_exists 'pacman'; then
  log::log 'pacman executable not found'
  exit 0
fi

readonly src_file="${HOME}/.etc/pacman.conf"
readonly dest_file='/etc/pacman.conf'
files::root_copy "${src_file}" "${dest_file}"
