#!/usr/bin/env bash

# @description Enable the journalctl-vacuum.timer user unit that periodically vacuums the journal.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

systemctl::enable_user_service_unit 'journalctl-vacuum.timer'
