#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_no_args "$@"

enable_user_service_unit 'journalctl-vacuum.timer'
