#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! dir_exists '/etc/ssh/sshd_config.d'; then
  die '/etc/ssh/sshd_config.d does not exist'
fi

readonly src_file="${HOME}/.etc/sshd.conf"
readonly dest_file='/etc/ssh/sshd_config.d/sshd.conf'

orig_hash="$(file_hash "${dest_file}")" || exit 1
readonly orig_hash
root_copy_file "${src_file}" "${dest_file}"
cur_hash="$(file_hash "${dest_file}")" || exit 1
readonly cur_hash

if [[ "${orig_hash}" != "${cur_hash}" ]]; then
  restart_system_service_if_enabled 'sshd.service'
fi
