#!/usr/bin/env bash

# @description Install the sshd drop-in config file, restarting sshd.service if its config changed.
# @noargs
# @exitcode 1 /etc/ssh/sshd_config.d does not exist

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

if ! dirs::exists '/etc/ssh/sshd_config.d'; then
  log::die '/etc/ssh/sshd_config.d does not exist'
fi

readonly src_file="${HOME}/.etc/sshd.conf"
readonly dest_file='/etc/ssh/sshd_config.d/sshd.conf'

orig_hash="$(files::hash_if_exists "${dest_file}")"
readonly orig_hash
files::root_copy "${src_file}" "${dest_file}"
cur_hash="$(files::hash_if_exists "${dest_file}")"
readonly cur_hash

if [[ "${orig_hash}" != "${cur_hash}" ]]; then
  systemctl::restart_system_service_if_enabled 'sshd.service'
fi
