#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_no_args "$@"

if ! executable_exists 'sshd'; then
  exit 0
fi

if is_debian || is_ubuntu; then
  enable_system_service_unit 'ssh.service'
elif is_arch || is_cachyos || is_fedora || is_leap || is_tumbleweed; then
  enable_system_service_unit 'sshd.service'
else
  die "Unexpected distro: $(os_id)"
fi
