#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! commands::executable_exists 'sshd'; then
  exit 0
fi

if os::is_debian || os::is_ubuntu; then
  systemctl::enable_system_service_unit 'ssh.service'
elif os::is_arch || os::is_cachyos || os::is_fedora || os::is_leap || os::is_tumbleweed; then
  systemctl::enable_system_service_unit 'sshd.service'
else
  log::die "Unexpected distro: $(os::id)"
fi
