#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! executable_exists 'sshd'; then
  exit 0
fi

if is_ubuntu; then
  readonly service_name='ssh'
else
  readonly service_name='sshd'
fi

enable_system_service_unit "${service_name}.service"
