#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.sh"
check_no_args "$@"

if ! executable_exists 'dnf'; then
  log 'dnf executable not found'
  exit 0
fi

for repo in 'rpmfusion-free-release' 'rpmfusion-nonfree-release'; do
  if ! dnf list --installed "${repo}" > /dev/null 2>&1 && prompt_yn "Add ${repo} repository?"; then
    sudo dnf install "https://mirrors.rpmfusion.org/free/fedora/${repo}-$(rpm --eval='%fedora').noarch.rpm"
  fi
done
