#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

readonly link_file='/etc/dnf/dnf.conf'
readonly target_file="${HOME}/.etc/dnf.conf"

if ! is_fedora; then
  exit 0
fi
if ! executable_exists 'dnf'; then
  log 'dnf executable not found'
  exit 0
fi

copy_system_file "${target_file}" "${link_file}"
