#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../../lib/functions.bash"
check_no_args "$@"

if ! is_fedora; then
  exit 0
fi
if ! executable_exists 'dnf'; then
  log 'dnf executable not found'
  exit 0
fi

readonly src_file="${HOME}/.etc/dnf.conf"
readonly dest_file='/etc/dnf/dnf.conf'
copy_system_file "${src_file}" "${dest_file}"
