#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

if [[ ! -f "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]]; then
  log 'Nix package manager not installed'
  exit 0
fi

log 'Installing Nix packages'
# shellcheck disable=SC1091
source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
export NIXPKGS_ALLOW_UNFREE='1'
get_packages_list 'nixpkgs' | xargs printf -- 'nixpkgs.%s\n' | xargs nix-env --install --attr

if [[ ! -L "${HOME}/.local/share/fonts/nix" ]]; then
  log 'Updating font cache'
  mkdir --parents "${HOME}/.local/share/fonts"
  ln --symbolic --force "${HOME}/.nix-profile/share/fonts" "${HOME}/.local/share/fonts/nix"
  fc-cache --force
fi
log 'Installed Nix packages'
