#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! executable_exists 'nix-store'; then
  exit 0
fi

enable_user_service_unit 'home-manager-optimization.timer'
