#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_no_args "$@"

if ! executable_exists 'nix-collect-garbage' || ! executable_exists 'nix-store'; then
  exit 0
fi

enable_user_service_unit 'home-manager-cleanup.timer'
