#!/usr/bin/env bash

# @description Enable the home-manager-cleanup.timer user unit when the Nix garbage-collection tools are installed.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

if ! commands::executable_exists 'nix-collect-garbage' || ! commands::executable_exists 'nix-store'; then
  exit 0
fi

systemctl::enable_user_service_unit 'home-manager-cleanup.timer'
