#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

readonly service_desc='journalctl-vacuum'
readonly service_unit='journalctl-vacuum.timer'
readonly required_executable='journalctl'
readonly system_or_user='user'

enable_service "${service_desc}" "${service_unit}" "${required_executable}" "${system_or_user}"
