#!/usr/bin/env bash

# @description Enable the appropriate SSH server system service unit for the detected distro.
# @noargs
# @exitcode 1 distro is not recognized

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

if ! commands::executable_exists 'sshd'; then
  exit 0
fi

if os::is_debian || os::is_ubuntu; then
  systemctl::enable_system_service_unit 'ssh.service'
elif os::is_arch || os::is_cachyos || os::is_fedora || os::is_leap || os::is_tumbleweed; then
  systemctl::enable_system_service_unit 'sshd.service'
else
  log::die "Unexpected distro: $(os::id)"
fi
