#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/../lib/functions.sh"
check_no_args "$@"

readonly old_history_file="${HOME}/.bash_history"
readonly new_history_file="${HISTFILE}"

move_file "${old_history_file}" "${new_history_file}"

