#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../../lib/functions.bash"
check_no_args "$@"

readonly old_history_file="${HOME}/.bash_history"
readonly new_history_file="${HISTFILE}"

move_file "${old_history_file}" "${new_history_file}"
