#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

readonly bash_logout_file="${HOME}/.bash_logout"

if [[ ! -f "${bash_logout_file}" ]]; then
  exit 0
fi
if ! prompt_yn "Delete ${bash_logout_file}?"; then
  exit 0
fi

log "Removing: ${bash_logout_file}"
rm "${bash_logout_file}"
log "Removed: ${bash_logout_file}"
