#!/usr/bin/env bash

# @description Enable systemd user lingering for the current user so user services run without an active session.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if [[ "$(loginctl show-user "${USER}" --property='Linger')" == 'Linger=yes' ]]; then
  exit 0
fi
if ! prompt::yn "Set ${USER} to linger?"; then
  exit 0
fi

log::log 'Setting user to linger'
sudo loginctl enable-linger "${USER}"
log::log 'Set user to linger'
