#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! commands::executable_exists 'rustup'; then
  exit 0
fi
if [[ "$(rustup toolchain list)" == 'stable'* ]]; then
  exit 0
fi
if ! prompt::yn 'Set rustup toolchain to stable?'; then
  exit 0
fi

log::log 'Setting rustup toolchain to stable'
rustup toolchain install 'stable'
log::log 'Set rustup toolchain to stable'
