#!/usr/bin/env bash

# @description Set the system locale to en_US.UTF-8, generating it if necessary.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

if localectl | grep::contains_exactly 'LANG=en_US.UTF-8'; then
  exit 0
fi
if ! prompt::yn 'Set locale to en_US.UTF8?'; then
  exit 0
fi

log::log 'Setting locale to en_US.UTF-8'
if ! grep::file_contains_regex '/etc/locale.gen' '^en_US.UTF-8 UTF-8'; then
  files::root_append_to '/etc/locale.gen' 'en_US.UTF-8 UTF-8'
fi
sudo locale-gen
sudo localectl set-locale 'LANG=en_US.UTF-8'
log::log 'Set locale to en_US.UTF-8'
