#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

if [[ -f "${HOME}/.local/bin/jetbrains-toolbox" ]]; then
  exit 0
fi
if ! prompt_yn 'Install JetBrains Toolbox?'; then
  exit 0
fi

log 'Installing JetBrains Toolbox'
mkdir --parents "${HOME}/.local/share/JetBrains/Toolbox/bin"
archive_url="$(dl 'https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release' | jq --raw-output '.TBA[0].downloads.linux.link')"
readonly archive_url
dl "${archive_url}" | tar --extract --gzip --directory="${HOME}/.local/share/JetBrains/Toolbox/bin" --strip-components='1'
chmod +x "${HOME}/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox"
mkdir --parents "${HOME}/.local/bin"
ln --symbolic --force "${HOME}/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox" "${HOME}/.local/bin/jetbrains-toolbox"
log 'Installed JetBrains Toolbox'
