#!/usr/bin/env bash

# @description Copy the AppImage AppArmor sysctl config into /etc/sysctl.d and reload sysctl if it changed.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

readonly src_file="${HOME}/.etc/sysctl-appimage-apparmor.conf"
readonly dest_file='/etc/sysctl.d/appimage-apparmor.conf'

# Copy instead of symlink - see 'protected_symlinks' in https://www.kernel.org/doc/Documentation/sysctl/fs.txt
orig_hash="$(files::hash_if_exists "${dest_file}")"
readonly orig_hash
files::root_copy "${src_file}" "${dest_file}"
cur_hash="$(files::hash_if_exists "${dest_file}")"
readonly cur_hash

if [[ "${orig_hash}" != "${cur_hash}" ]]; then
  system::reload_sysctl_conf
fi
