#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

readonly src_file="${HOME}/.etc/sysctl-enforce-ip-forward.service"
readonly dest_file='/etc/systemd/system/enforce-ip-forward.service'

# Copy instead of symlink - see 'protected_symlinks' in https://www.kernel.org/doc/Documentation/sysctl/fs.txt
files::root_copy "${src_file}" "${dest_file}"
