#!/usr/bin/env bash

## THIS SCRIPT HAS BEEN DISABLED FROM AUTOMATICALLY RUNNING BY MAKING IT NON-EXECUTABLE

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::check_no_args "$@"

readonly src_file="${HOME}/.etc/sysctl-rootless-docker.conf"
readonly dest_file='/etc/sysctl.d/rootless-docker.conf'

# Copy instead of symlink - see 'protected_symlinks' in https://www.kernel.org/doc/Documentation/sysctl/fs.txt
orig_hash="$(files::hash "${dest_file}")"
readonly orig_hash
files::root_copy "${src_file}" "${dest_file}"
cur_hash="$(files::hash "${dest_file}")"
readonly cur_hash

if [[ "${orig_hash}" != "${cur_hash}" ]]; then
  system::reload_sysctl_conf
fi
