#!/usr/bin/env bash

# @description Copy the enforce-ip-forward systemd service unit into /etc/systemd/system.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

readonly src_file="${HOME}/.etc/sysctl-enforce-ip-forward.service"
readonly dest_file='/etc/systemd/system/enforce-ip-forward.service'

# Copy instead of symlink - see 'protected_symlinks' in https://www.kernel.org/doc/Documentation/sysctl/fs.txt
files::root_copy "${src_file}" "${dest_file}"
