#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

readonly src_file="${HOME}/.etc/sysctl-max-user-watches.conf"
readonly dest_file='/etc/sysctl.d/max-user-watches.conf'

# Copy instead of symlink - see 'protected_symlinks' in https://www.kernel.org/doc/Documentation/sysctl/fs.txt
readonly orig_hash="$(file_hash "${dest_file}")"
root_copy_file "${src_file}" "${dest_file}"
readonly cur_hash="$(file_hash "${dest_file}")"

if [[ "${orig_hash}" != "${cur_hash}" ]]; then
  reload_sysctl_conf
fi
