#!/usr/bin/env bash

# @description Enable the enforce-ip-forward systemd system service unit.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

systemctl::enable_system_service_unit 'enforce-ip-forward.service'
