#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/../lib/functions.sh"
check_no_args "$@"

if ! executable_exists 'rustup'; then
  exit 0
fi
if [[ "$(rustup toolchain list)" == 'stable'* ]]; then
  exit 0
fi
if ! prompt_yn 'Set rustup toolchain to stable?'; then
  exit 0
fi

log 'Setting rustup toolchain to stable'
rustup toolchain install 'stable'
log 'Set rustup toolchain to stable'
