#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_no_args "$@"

if ! executable_exists 'aa-enabled'; then
  exit 0
fi

enable_system_service_unit 'apparmor.service'
