#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../../lib/functions.bash"
check_no_args "$@"

if executable_exists 'dockerd'; then
  enable_system_service_unit 'docker.service'
fi

if executable_exists 'containerd'; then
  enable_system_service_unit 'containerd.service'
fi
