#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

if executable_exists 'nfsstat'; then
  enable_system_service_unit 'nfsv4-server.service'
fi
