#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! commands::executable_exists 'dockerd'; then
  exit 0
fi

readonly src_file="${HOME}/.etc/docker-daemon.json"
readonly dest_file='/etc/docker/daemon.json'

orig_hash="$(files::hash "${dest_file}")"
readonly orig_hash
files::root_copy "${src_file}" "${dest_file}"
cur_hash="$(files::hash "${dest_file}")"
readonly cur_hash

if [[ "${orig_hash}" != "${cur_hash}" ]]; then
  systemctl::restart_system_service_if_enabled 'docker.service'
fi
