#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! executable_exists 'dockerd'; then
  exit 0
fi

readonly src_file="${HOME}/.etc/docker-daemon.json"
readonly dest_file='/etc/docker/daemon.json'

orig_hash="$(file_hash "${dest_file}")"
readonly orig_hash
root_copy_file "${src_file}" "${dest_file}"
cur_hash="$(file_hash "${dest_file}")"
readonly cur_hash

if [[ "${orig_hash}" != "${cur_hash}" ]]; then
  restart_system_service_if_enabled 'docker.service'
fi
