#!/usr/bin/env bash

# @description Disable the system docker service and install rootless docker as a user service.
# @noargs

## THIS SCRIPT HAS BEEN DISABLED FROM AUTOMATICALLY RUNNING BY MAKING IT NON-EXECUTABLE

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::check_no_args "$@"

if ! commands::executable_exists 'dockerd'; then
  log::log 'dockerd executable not found'
  exit 0
fi

if systemctl::user_service_unit_file_exists 'docker.service'; then
  exit 0
fi

if ! prompt::ny 'Enable rootless Docker?'; then
  exit 0
fi

if ! commands::executable_exists 'dockerd-rootless-setuptool.sh'; then
  log::log 'dockerd-rootless-setuptool.sh executable not found'
  exit 0
fi

systemctl::disable_system_service_unit 'docker.service'
systemctl::disable_system_service_unit 'docker.socket'

sudo rm --force '/var/run/docker.sock'

log::log 'Running rootless setup script'
dockerd-rootless-setuptool.sh install
log::log 'Ran rootless setup script'

systemctl::enable_user_service_unit 'docker.service'
