#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! executable_exists 'dockerd'; then
  exit 0
fi

enable_system_service_unit 'docker.service'

if ! executable_exists 'containerd'; then
  exit 0
fi

enable_system_service_unit 'containerd.service'
