#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! commands::executable_exists 'dockerd'; then
  exit 0
fi

systemctl::enable_system_service_unit 'docker.service'

if ! commands::executable_exists 'containerd'; then
  exit 0
fi

systemctl::enable_system_service_unit 'containerd.service'
