#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

readonly service_desc='SSH Agent'
readonly service_unit='ssh-agent.service'
readonly required_executable='ssh-agent'
readonly system_or_user='user'

enable_service "${service_desc}" "${service_unit}" "${required_executable}" "${system_or_user}"
