#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

readonly service_desc='SSH Agent'
readonly service_unit='ssh-agent.service'

enable_user_service "${service_desc}" "${service_unit}"
