#!/usr/bin/env bash

# @description Copy a file while displaying a textual progress bar driven by strace write counts.
# @arg $1 src Source file path.
# @arg $2 dest Destination file path.
# @stdout Animated progress bar that updates in place.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is not statically followable
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_exactly_2_args "$@"
readonly SRC="$1"
readonly DEST="$2"

# Copy file with a progress bar
strace --quiet -ewrite cp -- "${SRC}" "${DEST}" 2>&1 | awk '{
  count += $NF
  if (count % 10 == 0) {
    percent = count / total_size * 100
    printf "%3d%% [", percent
    for (i=0;i<=percent;i++)
      printf "="
      printf ">"
      for (i=percent;i<100;i++)
        printf " "
        printf "]\r"
  }
}
END { print "" }' total_size="$(stat --format='%s' "${SRC}")" count=0
