#!/usr/bin/env bash

# @description Pull the latest images for all services in the current directory's docker compose project.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is not statically followable
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

docker compose pull
