#!/usr/bin/env bash

# @description List packages installed by home-manager in the current generation.
# @noargs
# @stdout One installed home-manager package name per line.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

home-manager packages
