#!/usr/bin/env bash

# @description Activate the home-manager flake in $HOME_MANAGER_DIR and print the generations diff.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

home-manager switch --flake "${HOME_MANAGER_DIR}"
home-manager-generations-diff
