#!/usr/bin/env bash

# @description Lowercase text from stdin, or rename each given file to a lowercase name.
# @arg $@ files Optional file paths to rename to their lowercased basenames; omit when piping text on stdin.
# @stdout When reading stdin: input text with all characters lowercased.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced from SCRIPTS_DIR at runtime
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"

if args::stdin_exists; then
  args::check_no_args "$@"
  tr '[:upper:]' '[:lower:]'
else
  args::check_at_least_1_arg "$@"
  for file in "$@"; do
    dirname="$(dirname -- "${file}")"
    filename="$(basename -- "${file}")"
    lower_filename="$(printf '%s\n' "${filename}" | tr '[:upper:]' '[:lower:]')"
    target_file="${dirname}/${lower_filename}"
    if [[ "${lower_filename}" != "${filename}" ]]; then
      mv -- "${file}" "${target_file}"
      log::log "${file} -> ${target_file}"
    else
      log::log "${file} not renamed"
    fi
  done
fi
