#!/usr/bin/env bash

# @description Swap the contents at two paths (both files or both directories) via a temporary intermediate.
# @arg $1 path_a First path to swap.
# @arg $2 path_b Second path to swap.
# @exitcode 1 One path is a file and the other a directory, or either path does not exist.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_exactly_2_args "$@"
readonly PATH_A="$1"
readonly PATH_B="$2"

if { files::exists "${PATH_A}" && files::exists "${PATH_B}"; } || { dirs::exists "${PATH_A}" && dirs::exists "${PATH_B}"; }; then
  files::create_temp temp_file
  # shellcheck disable=SC2154 # temp_file assigned by files::create_temp via nameref
  mv -- "${PATH_A}" "${temp_file}"
  mv -- "${PATH_B}" "${PATH_A}"
  mv -- "${temp_file}" "${PATH_B}"
  log::log "${PATH_A} <-> ${PATH_B}"
else
  if files::any_exists "${PATH_A}" && files::any_exists "${PATH_B}"; then
    log::die "Cannot swap file and directory"
  fi
  if ! files::any_exists "${PATH_A}"; then
    log::die "${PATH_A} does not exist"
  fi
  if ! files::any_exists "${PATH_B}"; then
    log::die "${PATH_B} does not exist"
  fi
fi
