#!/usr/bin/env bash

# @description Print the host's public IPv4 and IPv6 addresses by querying ifconfig.me.
# @noargs
# @stdout One line each for the IPv4 and IPv6 public addresses.

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

http::curl --ipv4 --write-out '\n' 'ifconfig.me/ip'
http::curl --ipv6 --write-out '\n' 'ifconfig.me/ip'
