#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../setup/functions.bash"
check_not_root
check_no_args "$@"

if [[ ! -f "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]] && prompt_yn 'Install Nix?'; then
  log 'Installing Nix'
  if [[ ! -d '/nix' ]]; then
    sudo mkdir '/nix'
  fi
  sudo chmod 755 '/nix'
  sudo chown --recursive "${USER}:" '/nix'
  download 'https://nixos.org/nix/install' | sh -s -- --no-daemon
  log 'Installed Nix'
fi

if [[ -f "${HOME}/.nix-profile/etc/profile.d/nix.sh" && ! -f "${HOME_MANAGER_DIR}/flake.lock" ]] && prompt_yn 'Install Nix home-manager and packages?'; then
  log 'Installing Nix home-manager and packages'
  # shellcheck disable=SC1091
  source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
  write-home-manager-packages
  nix run nixpkgs#home-manager -- switch --flake "${HOME_MANAGER_DIR}"
  log 'Installed Nix home-manager and packages'
fi
