#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if is_debian; then
  log "Enabling backports repo"
  echo "deb http://deb.debian.org/debian $(os_codename)-backports main" | \
    sudo tee '/etc/apt/sources.list.d/backports.list' > '/dev/null'
  log "Enabled backports repo"
fi
