#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if is_debian; then
  log "Enabling backports repo"
  echo "deb http://deb.debian.org/debian $(os_codename)-backports main" | \
    sudo tee '/etc/apt/sources.list.d/backports.list' > '/dev/null'
  log "Enabled backports repo"
fi

if is_arch || is_manjaro || is_endeavour; then
  if pacman-key --list-keys | contains_exactly_ignore_case 'FBA220DFC880C036'; then
    exit 0
  fi
  log 'Adding Chaotic AUR keyring and mirror list'
  sudo pacman-key --recv-key 'FBA220DFC880C036' --keyserver 'keyserver.ubuntu.com'
  sudo pacman-key --lsign-key 'FBA220DFC880C036'
  sudo pacman --upgrade --noconfirm \
    'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' \
    'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
  log 'Added Chaotic AUR keyring and mirror list'
fi
