#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_no_args "$@"

if ! prompt_yn 'Update distro packages?'; then
  exit 0
fi

if executable_exists 'apt'; then
  sudo apt update
  sudo apt upgrade --yes
elif executable_exists 'dnf'; then
  sudo dnf upgrade
elif executable_exists 'pacman'; then
  sudo pacman --sync --refresh --sysupgrade
fi
