#!/usr/bin/env bash

# @description Interactively update all installed distro packages using the detected package manager (apt, dnf, or pacman).
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! prompt::yn 'Update distro packages?'; then
  exit 0
fi

if commands::executable_exists 'apt'; then
  sudo apt update
  sudo apt upgrade --yes
elif commands::executable_exists 'dnf'; then
  sudo dnf upgrade
elif commands::executable_exists 'pacman'; then
  sudo pacman --sync --refresh --sysupgrade
fi
