#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if executable_exists 'tailscale'; then
  exit 0
fi
if ! prompt_yn 'Install Tailscale?'; then
  exit 0
fi

log 'Installing Tailscale'
download 'https://tailscale.com/install.sh' | sh
log 'Installed Tailscale'
