#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if executable_exists 'tailscale'; then
  exit 0
fi
if ! prompt_yn 'Install Tailscale?'; then
  exit 0
fi

log 'Installing Tailscale'
if is_ubuntu && [[ "$(lsb_release --codename --short)" == 'jammy' ]]; then
  # https://techoverflow.net/2022/08/26/how-to-fix-apt-error-no_pubkey-458ca832957f5868/
  download 'https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg' | sudo tee '/usr/share/keyrings/tailscale-archive-keyring.gpg' >/dev/null
  download 'https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list' | sudo tee '/etc/apt/sources.list.d/tailscale.list' > /dev/null
  sudo apt-get update
fi
download 'https://tailscale.com/install.sh' | sh
log 'Installed Tailscale'
