#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if ! prompt_yn 'Install packages via external scripts?'; then
  exit 0
fi

# wrapper around curl to disable reading the config that is intended for interactive use
function curl() {
  command curl --disable "$@"
}
export -f curl

# wrapper around wget to disable reading the config that is intended for interactive use
function wget() {
  command wget --no-config "$@"
}
export -f wget

for script_info in "$(get_install_scripts)"; do
  IFS=' ' read -r name executable url <<< "${script_info}"
  if executable_exists "${executable}"; then
    log "${name} is already installed"
    continue
  fi
  if ! prompt_yn "Install ${name}?"; then
    continue
  fi
  log "Installing ${name} from ${url}"
  download "${url}" | sh
  log "Installed ${name} from ${url}"
done
