#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_no_args "$@"

if ! prompt_yn 'Install distro packages?'; then
  exit 0
fi

mapfile -t packages < <(get_distro_packages "$(os_id)" "$(os_codename)")
readonly packages

if executable_exists 'apt'; then
  sudo apt install --install-recommends --yes "${packages[@]}"
elif executable_exists 'dnf'; then
  sudo dnf install --assumeyes "${packages[@]}"
elif executable_exists 'pacman'; then
  sudo pacman --sync --needed --noconfirm "${packages[@]}"
fi
