#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

readonly name='Docker'
readonly executable='dockerd'
readonly url='https://get.docker.com'

# wrapper around curl to disable reading the config that is intended for interactive use
function curl() {
  command curl --disable "$@"
}

# wrapper around wget to disable reading the config that is intended for interactive use
function wget() {
  command wget --no-config "$@"
}

function main() {
  if commands::executable_exists "${executable}"; then
    exit 0
  fi
  if ! prompt::yn "Install ${name}?"; then
    exit 0
  fi
  export -f curl wget
  log::log "Installing ${name} via: ${url}"
  downloads::download_and_run_script "${url}"
  log::log "Installed ${name} via: ${url}"
}

main "$@"
