#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if ! is_ubuntu; then
  exit 0
fi
if ! executable_exists 'snap'; then
  exit 0
fi
if ! prompt_yn 'Remove snap?'; then
  exit 0
fi

log 'Removing snaps'
while [[ "$(snap list 2> '/dev/null' | wc --lines)" -gt 0 ]]; do
  for snap in $(snap list | tail -n '+2' | cut --delimiter=' ' --fields='1'); do
    if sudo snap remove --purge "${snap}" &> '/dev/null'; then
      log "Removed snap: ${snap}"
    fi
  done
done
log 'Removed snaps'

log 'Disabling snapd services'
sudo systemctl disable --now 'snapd.service'
sudo systemctl disable --now 'snapd.socket'
sudo systemctl disable --now 'snapd.seeded.service'
log 'Disabled snapd services'

log 'Masking snapd'
sudo systemctl mask 'snapd'
log 'Masked snapd'

log 'Removing snapd package'
sudo apt-get remove --autoremove --yes 'snapd'
log 'Removed snapd package'

log 'Writing /etc/apt/preferences.d/disable-snap.pref'
{
  echo 'Package: snapd'
  echo 'Pin: release a=*'
  echo 'Pin-Priority: -10'
} | sudo tee '/etc/apt/preferences.d/disable-snap.pref' > '/dev/null'

log 'Updating apt package index'
apt-get update
log 'Updated apt package index'

existing_mounts="$(grep --invert '^\s*#' '/etc/fstab' | awk '{ print $2 }')"
readonly existing_mounts

for dir in '/snap' '/var/snap' '/var/lib/snapd' '/var/cache/snapd' '/root/snap'; do
  if [[ -d "${dir}" ]]; then
    if grep --quiet --fixed-strings --line-regexp "${dir}" <<< "${existing_mounts}"; then
      # if this dir exists in fstab, it is likely because I have a btrfs subvolume mounted at that dir
      log "Removing all files in: ${dir}"
      sudo rm -rf "${dir:?}/"*
      log "Removed all files in: ${dir}"
    else
      log "Removing: ${dir}"
      sudo rm -rf "${dir}"
      log "Removed: ${dir}"
    fi
  fi
done

for dir in "/home/"*; do
  if [[ -d "${dir}/snap" ]]; then
    if grep --quiet --fixed-strings --line-regexp "${dir}" <<< "${existing_mounts}"; then
      # if this dir exists in fstab, it is likely because I have a btrfs subvolume mounted at that dir
      log "Removing all files in: ${dir}/snap"
      sudo rm -rf "${dir}/snap/"*
      log "Removed all files in: ${dir}/snap"
    else
      log "Removing: ${dir}/snap"
      sudo rm -rf "${dir}/snap"
      log "Removed: ${dir}/snap"
    fi
  fi
done
