#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

readonly name='Cockpit'
readonly executable='cockpit-bridge'

if ! is_server; then
  exit 0
fi
# On Debian and Ubuntu, install cockpit from backports repo.
# Other distros (Arch and Fedora) can install from the regular repos.
if ! is_debian && ! is_ubuntu; then
  exit 0
fi
if executable_exists "${executable}"; then
  exit 0
fi
if ! prompt_yn "Install ${name}?"; then
  exit 0
fi

log "Installing ${name}"
sudo apt install --yes --target-release "$(os_codename)-backports" cockpit
log "Installed ${name}"
