#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

readonly name='Cockpit'
readonly executable='cockpit-bridge'

if ! hosts::is_server; then
  exit 0
fi
# On Debian and Ubuntu, install cockpit from backports repo.
# Other distros can install from the regular repos.
if os::is_debian || os::is_ubuntu; then
  :
elif os::is_arch || os::is_cachyos || os::is_fedora || os::is_leap || os::is_tumbleweed; then
  exit 0
else
  log::die "Unexpected distro: $(os::id)"
fi
if commands::executable_exists "${executable}"; then
  exit 0
fi
if ! prompt::yn "Install ${name}?"; then
  exit 0
fi

log::log "Installing ${name}"
sudo apt install --yes --target-release "$(os::codename)-backports" cockpit
log::log "Installed ${name}"
