#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

readonly name='Webmin'
readonly executable='webmin'
readonly url='https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repos.sh'

# wrapper around curl to disable reading the config that is intended for interactive use
function curl() {
  command curl --disable "$@"
}

# wrapper around wget to disable reading the config that is intended for interactive use
function wget() {
  command wget --no-config "$@"
}

function main() {
  if ! hosts::is_server; then
    exit 0
  fi
  if os::is_debian || os::is_ubuntu || os::is_fedora; then
    :
  elif os::is_arch || os::is_cachyos || os::is_leap || os::is_tumbleweed; then
    exit 0
  else
    log::die "Unexpected distro: $(os::id)"
  fi
  if commands::executable_exists "${executable}"; then
    exit 0
  fi
  if ! prompt::yn "Install ${name}?"; then
    exit 0
  fi
  export -f curl wget
  log::log "Adding ${name} repo"
  downloads::download_and_run_script_as_root "${url}" --force
  log::log "Added ${name} repo"
  log::log "Installing ${name}"
  if commands::executable_exists 'apt'; then
    sudo apt install --yes --install-recommends 'webmin'
  elif commands::executable_exists 'dnf'; then
    sudo dnf install 'webmin'
  else
    log::die 'Expected either apt or dnf to be available'
  fi
  log::log "Installed ${name}"
}

main "$@"
