#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

readonly name='Webmin'
readonly executable='webmin'
readonly url='https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repos.sh'

if ! is_server; then
  exit 0
fi
if ! is_debian && ! is_ubuntu && ! is_fedora; then
  exit 0
fi
if executable_exists "${executable}"; then
  exit 0
fi
if ! prompt_yn "Install ${name}?"; then
  exit 0
fi

# wrapper around curl to disable reading the config that is intended for interactive use
function curl() {
  command curl --disable "$@"
}
export -f curl

# wrapper around wget to disable reading the config that is intended for interactive use
function wget() {
  command wget --no-config "$@"
}
export -f wget

log "Adding ${name} repo"
download_and_run_script_as_root "${url}" --force
log "Added ${name} repo"

log "Installing ${name}"
if executable_exists 'apt'; then
  sudo apt install --yes --install-recommends 'webmin'
elif executable_exists 'dnf'; then
  sudo dnf install 'webmin'
else
  die 'Expected either apt or dnf to be available'
fi
log "Installed ${name}"
