#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! executable_exists 'nix' && prompt_yn 'Install Nix?'; then
  log 'Installing Nix'
  if ! dir_exists '/nix'; then
    root_create_dir '/nix'
  fi
  sudo chmod 755 '/nix'
  sudo chown --recursive "${USER}:" '/nix'
  download_and_run_script 'https://nixos.org/nix/install' --no-daemon --no-modify-profile
  log 'Installed Nix'
fi

if ! executable_exists 'home-manager' && prompt_yn 'Install Nix home-manager and packages?'; then
  log 'Installing Nix home-manager and packages'
  # shellcheck disable=SC1091
  source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
  write-home-manager-packages
  home_manager_release="$(grep --only-matching --perl-regexp '(?<=github:nix-community/)home-manager/release-\d{2}\.\d{2}' "${HOME_MANAGER_DIR}/flake.nix")" || exit 1
  readonly home_manager_release
  nix run "${home_manager_release}" -- init --switch --flake "${HOME_MANAGER_DIR}"
  if executable_exists 'non-nixos-gpu-setup'; then
    sudo "$(which non-nixos-gpu-setup)"
  fi
  log 'Installed Nix home-manager and packages'
fi
