#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! executable_exists 'nix' && prompt_yn 'Install Nix?'; then
  log 'Installing Nix'
  if [[ ! -d '/nix' ]]; then
    sudo mkdir '/nix'
  fi
  sudo chmod 755 '/nix'
  sudo chown --recursive "${USER}:" '/nix'
  download_and_run_script 'https://nixos.org/nix/install' --no-daemon --no-modify-profile
  log 'Installed Nix'
fi

if ! executable_exists 'home-manager' && prompt_yn 'Install Nix home-manager and packages?'; then
  log 'Installing Nix home-manager and packages'
  # shellcheck disable=SC1091
  source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
  write-home-manager-packages
  nix run nixpkgs#home-manager -- switch --flake "${HOME_MANAGER_DIR}"
  log 'Installed Nix home-manager and packages'
fi
