#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! file_exists "${SDKMAN_DIR}/bin/sdkman-init.sh" && prompt_yn 'Install SDKMAN?'; then
  log 'Installing SDKMAN'
  if dir_exists "${SDKMAN_DIR}"; then
    # chezmoi will have created ~/.sdkman and the SDKMAN install script assumes
    # that the presence of this directory means that SDKMAN has already been
    # installed and will not actually install SDKMAN. This directory should only
    # contain a symlink to ~/.config/sdkman/config. This symlink will be
    # re-created later in this script.
    rm --recursive "${SDKMAN_DIR}"
  fi
  # Retry due to random timeouts
  readonly base_sleep_time=30
  tries=0
  until download_and_run_script 'https://get.sdkman.io?rcupdate=false'; do
    ((tries += 1))
    if ((tries > 10)); then
      die "Failed to install SDKMAN in 10 tries"
    fi
    rm -rf "${SDKMAN_DIR}"
    sleep "$((base_sleep_time * tries))"
  done
  log 'Installed SDKMAN'
fi

if file_exists "${SDKMAN_DIR}/bin/sdkman-init.sh" && prompt_yn 'Install SDKMAN packages?'; then
  sdkman-update
fi

if file_exists "${HOME}/.config/sdkman/config"; then
  link_file "${HOME}/.config/sdkman/config" "${SDKMAN_DIR}/etc/config"
fi
