#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if ! executable_exists 'flatpak'; then
  log 'flatpak executable not found'
  exit 0
fi

if ! flatpak remotes --user --columns=title | contains_word 'Flathub'; then
  log 'Adding Flathub flatpak repo'
  flatpak remote-add --user 'flathub' 'https://flathub.org/repo/flathub.flatpakrepo'
  log 'Added Flathub flatpak repo'
fi

if ! prompt_yn 'Install flatpak packages?'; then
  exit 0
fi

log 'Installing flatpak packages'
get_universal_packages 'flatpaks' | xargs --no-run-if-empty flatpak install --user --noninteractive
log 'Installed flatpak packages'

if flatpak list --user --app | grep --quiet --fixed-strings 'com.google.Chrome'; then
  flatpak override --user --filesystem="${HOME}/.local/share/applications:create" --filesystem="${HOME}/.local/share/icons:create" 'com.google.Chrome'
fi
