#!/usr/bin/env bash

# @description Add the Flathub remote (user scope) and install the configured Flatpak package list.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is not statically followable
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

if ! commands::executable_exists 'flatpak'; then
  log::log 'flatpak executable not found'
  exit 0
fi

if ! flatpak remotes --user --columns=title | grep::contains_word_ignore_case 'flathub'; then
  log::log 'Adding Flathub Flatpak repo'
  flatpak remote-add --user 'flathub' 'https://flathub.org/repo/flathub.flatpakrepo'
  log::log 'Added Flathub Flatpak repo'
fi

if ! prompt::yn 'Install Flatpak packages?'; then
  exit 0
fi

log::log 'Installing Flatpak packages'
packages::get_universal 'flatpak' | xargs --no-run-if-empty --max-args=100 flatpak install --user --noninteractive
log::log 'Installed Flatpak packages'

if flatpak list --user --app | grep::contains_exactly_ignore_case 'com.google.chrome'; then
  flatpak override --user \
    --filesystem="${XDG_DATA_HOME}/applications:create" \
    --filesystem="${XDG_DATA_HOME}/icons:create" \
    'com.google.Chrome'
fi
