#!/usr/bin/env bash

# @description Interactively install AppMan and the configured AppImage package list.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is not statically followable
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

if ! commands::executable_exists 'appman' && prompt::yn 'Install AppMan?'; then
  log::log 'Installing AppMan'
  readonly appman_location="${XDG_BIN_HOME}/appman"
  download 'https://raw.githubusercontent.com/ivan-hc/AM/main/APP-MANAGER' "${appman_location}"
  chmod +x "${appman_location}"
  log::log 'Installed AppMan'
fi

if ! commands::executable_exists 'appman' || ! prompt::yn 'Install AppImage packages'; then
  exit 0
fi

log::log 'Installing AppMan packages'
packages::get_universal 'appimage' | xargs --no-run-if-empty --max-args=1 appman install
log::log 'Installed AppMan packages'
