#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if executable_exists 'dockerd'; then
  exit 0
fi
if ! prompt_yn 'Install Docker Engine?'; then
  exit 0
fi

log 'Installing Docker Engine'
download 'https://get.docker.com' | sh
log 'Installed Docker Engine'
