#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if ! is_server; then
  exit 0
fi
if executable_exists 'casaos'; then
  exit 0
fi
if ! prompt_yn 'Install CasaOS?'; then
  exit 0
fi

log 'Installing CasaOS'
download 'https://get.casaos.io' | sudo bash
log 'Installed CasaOS'
