#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if is_server; then
  exit 0
fi

readonly toolbox_install_dir="${HOME}/.local/share/JetBrains/Toolbox/bin"
readonly toolbox_install_binary="${toolbox_install_dir}/jetbrains-toolbox"
readonly toolbox_release_info_url='https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release'
readonly local_bin_dir="${HOME}/.local/bin"
readonly local_bin_symlink="${local_bin_dir}/jetbrains-toolbox"

if [[ -f "${local_bin_symlink}" ]]; then
  exit 0
fi
if ! prompt_yn 'Install JetBrains Toolbox?'; then
  exit 0
fi

log 'Installing JetBrains Toolbox'
mkdir --parents "${toolbox_install_dir}"
mkdir --parents "${local_bin_dir}"
archive_url="$(download_and_cat "${toolbox_release_info_url}" | jq --raw-output '.TBA[0].downloads.linux.link')"
readonly archive_url
download_and_cat "${archive_url}" | tar --extract --gzip --directory="${toolbox_install_dir}" --strip-components='1'
chmod +x "${toolbox_install_binary}"
ln --symbolic --force "${toolbox_install_binary}" "${local_bin_symlink}"
log 'Installed JetBrains Toolbox'
