#!/usr/bin/env bash

# @description Download and install the latest JetBrains Toolbox tarball, symlinking the binary into the user bin dir.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if hosts::is_server; then
  exit 0
fi

readonly toolbox_install_dir="${XDG_DATA_HOME}/JetBrains/Toolbox/bin"
readonly toolbox_install_binary="${toolbox_install_dir}/jetbrains-toolbox"
readonly toolbox_release_info_url='https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release'
readonly local_bin_dir="${XDG_BIN_HOME}"
readonly local_bin_symlink="${local_bin_dir}/jetbrains-toolbox"

if files::exists "${local_bin_symlink}"; then
  exit 0
fi
if ! prompt::yn 'Install JetBrains Toolbox?'; then
  exit 0
fi

log::log 'Installing JetBrains Toolbox'
dirs::create "${toolbox_install_dir}" "${local_bin_dir}"
archive_url="$(
  downloads::download_and_cat "${toolbox_release_info_url}" \
    | jq --raw-output '.TBA[0].downloads.linux.link'
)"
readonly archive_url
downloads::download_and_cat "${archive_url}" \
  | tar --extract --gzip \
    --directory="${toolbox_install_dir}" \
    --strip-components=1
chmod +x "${toolbox_install_binary}"
symlinks::link_file "${toolbox_install_binary}" "${local_bin_symlink}"
log::log 'Installed JetBrains Toolbox'
