#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! hosts::is_work; then
  exit 0
fi
if ! os::is_ubuntu; then
  log::log 'This is a work computer, but not Ubuntu. Skipping installing AWS VPN Client'
  exit 0
fi
if packages::dpkg_package_installed 'awsvpnclient'; then
  exit 0
fi
if ! prompt::yn 'Install AWS VPN Client?'; then
  exit 0
fi

readonly public_key_target_file='/etc/apt/trusted.gpg.d/awsvpnclient_public_key.asc'
readonly list_target_file='/etc/apt/sources.list.d/aws-vpn-client.list'

log::log "Adding AWS VPN Client public key"
files::root_write "${public_key_target_file}" "$(
  downloads::download_and_cat \
    'https://d20adtppz83p9s.cloudfront.net/GTK/latest/debian-repo/awsvpnclient_public_key.asc'
)"
log::log "Added AWS VPN Client public key"

log::log "Adding AWS VPN Client source list file"
files::root_write "${list_target_file}" \
  "deb [arch=amd64] https://d20adtppz83p9s.cloudfront.net/GTK/latest/debian-repo ubuntu main"
log::log "Added AWS VPN Client source list file"

log::log 'Installing AWS VPN Client'
sudo apt update
sudo apt install --install-recommends --yes 'awsvpnclient'
log::log 'Installed AWS VPN Client'

if ! packages::dpkg_package_installed 'openvpn-systemd-resolved'; then
  log::log 'Installing openvpn-systemd-resolved and restarting systemd-resolved'
  sudo apt install 'openvpn-systemd-resolved'
  sudo systemctl restart 'systemd-resolved'
  log::log 'Installed openvpn-systemd-resolved and restarted systemd-resolved'
fi

log::log 'Downloading AWS VPN OVPN file'
readonly de_ovpn_file_url='https://raw.githubusercontent.com/rvenutolo/crypt/main/ovpn/de.ovpn'
readonly de_ovpn_file="${HOME}/de.ovpn"
download-decrypt "${de_ovpn_file_url}" "${de_ovpn_file}"
log::log 'Downloaded AWS VPN OVPN file'
