#!/usr/bin/env bash

# References:
# https://docs.aws.amazon.com/vpn/latest/clientvpn-user/client-vpn-connect-linux-install.html
# https://sailokesh.hashnode.dev/connecting-to-aws-vpn-client-on-ubuntu-2204-workaround?source=more_articles_bottom_blogs
# https://repost.aws/questions/QUNJeF_ja_Suykous7EvfX5Q/aws-client-vpn-on-ubuntu-22-04
# https://gist.github.com/tomaszgiba/4b0c04a6b4b0048e6a582b19133014b7#file-start_awsvpnclient-sh-L17
# https://gist.github.com/thiagozs/4d8c6e090a027fae3dd883163615f91e

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if ! is_work; then
  exit 0
fi
if [[ -d '/opt/awsvpnclient' ]]; then
  exit 0
fi
if ! is_ubuntu; then
  log 'This is a work computer, but not Ubuntu. Skipping installing AWS VPN Client'
  exit 0
fi
if ! prompt_yn 'Install AWS VPN Client?'; then
  exit 0
fi

if ! dpkg --status 'libssl1.1' > '/dev/null' 2>&1; then
  log 'Installing old libssl1.1 package for AWS VPN client'
  readonly libssl1_url='http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb'
  libssl1_deb="$(mktemp --suffix "__$(basename "${libssl1_url}")")"
  readonly libssl1_deb
  download "${libssl1_url}" "${libssl1_deb}"
  sudo apt-get install --yes "${libssl1_deb}"
  log 'Installed old libssl1.1 package for AWS VPN client'
fi

readonly repo_url='https://d20adtppz83p9s.cloudfront.net/GTK/latest/debian-repo'
readonly public_key_url="${repo_url}/awsvpnclient_public_key.asc"
readonly public_key_file='/etc/apt/trusted.gpg.d/awsvpnclient_public_key.asc'
readonly apt_list_file='/etc/apt/sources.list.d/aws-vpn-client.list'
download "${public_key_url}" | sudo tee "${public_key_file}" > '/dev/null'
sudo chmod 644 "${public_key_file}"
echo "deb [arch=amd64] ${repo_url} ubuntu-20.04 main" | sudo tee "${apt_list_file}" > '/dev/null'
sudo chmod 644 "${apt_list_file}"

log 'Installing AWS VPN Client'
sudo apt-get update
sudo apt-get install --yes awsvpnclient
log 'Installed AWS VPN Client'

log 'Downloading AWS VPN OVPN file'
readonly de_ovpn_file_url='https://raw.githubusercontent.com/rvenutolo/crypt/main/ovpn/de.ovpn'
readonly de_ovpn_file="${HOME}/de.ovpn"
download-decrypt "${de_ovpn_file_url}" "${de_ovpn_file}"
log 'Downloaded AWS VPN OVPN file'

log 'Installing openvpn-systemd-resolved and restarting systemd-resolved'
sudo apt-get install 'openvpn-systemd-resolved'
sudo systemctl restart 'systemd-resolved'
log 'Installed openvpn-systemd-resolved and restarted systemd-resolved'
