#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! is_work; then
  exit 0
fi

readonly connection_file_url='https://raw.githubusercontent.com/rvenutolo/crypt/main/misc/de-400.nmconnection'
readonly connection_file='/etc/NetworkManager/system-connections/de-400.nmconnection'

if file_exists "${connection_file}"; then
  exit 0
fi

if ! prompt_yn 'Install DE WIFI connection file?'; then
  exit 0
fi

log 'Installing DE WIFI connection file'
root_write_file "${connection_file}" "$(download-decrypt "${connection_file_url}")"
sudo chmod 600 "${connection_file}"
log 'Installed DE WIFI connection file'
