#!/usr/bin/env bash

# @description Install NVIDIA drivers via ubuntu-drivers (Ubuntu work hosts only).
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is not statically followable
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

if ! hosts::is_work; then
  exit 0
fi
if ! os::is_ubuntu; then
  log::log 'This is a work computer, but not Ubuntu. Skipping installing NVIDIA drivers'
  exit 0
fi
if dpkg-query --show --showformat='${Package};${Status}\n' 'nvidia-driver-*' 2> '/dev/null' \
  | grep::contains_regex_ignore_case '^nvidia-driver-[0-9][0-9][0-9];.*ok installed$'; then
  exit 0
fi
if ! prompt::yn 'Install NVIDIA drivers?'; then
  exit 0
fi

log::log 'Installing NVIDIA drivers'
sudo ubuntu-drivers install
log::log 'Installed NVIDIA drivers'
