#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if is_server; then
  exit 0
fi

readonly joplin_install_dir="${HOME}/.local/share/joplin"
readonly joplin_install_binary="${joplin_install_dir}/joplin"
readonly joplin_install_script_url='https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh'
readonly local_bin_dir="${HOME}/.local/bin"
readonly local_bin_symlink="${local_bin_dir}/joplin"

if [[ -f "${local_bin_symlink}" ]]; then
  exit 0
fi
if ! prompt_yn 'Install Joplin Desktop?'; then
  exit 0
fi

log 'Installing Joplin Desktop'
mkdir --parents "${joplin_install_dir}"
mkdir --parents "${local_bin_dir}"
download "${joplin_install_script_url}" | sed \
  --expression="s|*.AppImage|$(basename "${joplin_install_binary}")|g" \
  --expression="s|~/.joplin|${joplin_install_dir}|g" \
  --expression="s|\${HOME}/.joplin|${joplin_install_dir}|g" \
  --expression="s|Joplin.AppImage|$(basename "${joplin_install_binary}")|g" \
  --expression='s|wget|wget --no-config|g' \
  | bash
ln --symbolic --force "${joplin_install_binary}" "${local_bin_symlink}"
log 'Installed Joplin Desktop'
