#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

if ! is_fedora; then
  exit 0
fi
if ! rpm --quiet --query 'PackageKit-command-not-found'; then
  log 'PackageKit-command-not-found is not installed'
  exit 0
fi

readonly src_file="${HOME}/.etc/fedora_command_not_found.conf"
readonly dest_file='/etc/PackageKit/CommandNotFound.conf'
copy_system_file "${src_file}" "${dest_file}"
