#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_no_args "$@"

readonly src_file="${HOME}/.etc/network-manager-aws-vpn-dns-fix"
readonly dest_file='/etc/NetworkManager/dispatcher.d/99-vpn-dns-fix'
root_copy_file "${src_file}" "${dest_file}"
