#!/usr/bin/env bash

# @description Install the NetworkManager dispatcher script that fixes DNS resolution while connected to the AWS VPN.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

readonly src_file="${HOME}/.etc/network-manager-aws-vpn-dns-fix"
readonly dest_file='/etc/NetworkManager/dispatcher.d/99-vpn-dns-fix'
files::root_copy "${src_file}" "${dest_file}"
