#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

readonly target_file="${HOME}/.etc/hosts"
readonly link_file='/etc/hosts'
link_system_file "${target_file}" "${link_file}"
