#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../../lib/functions.bash"
check_no_args "$@"

readonly target_file="${HOME}/.etc/hosts"
readonly link_file='/etc/hosts'

link_file "${target_file}" "${link_file}"
