#!/usr/bin/env bash

# @description Remove the ~/.hushlogin file if present so the login banner is shown again.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

readonly hushlogin_file="${HOME}/.hushlogin"

if ! files::exists "${hushlogin_file}"; then
  exit 0
fi
if ! prompt::yn "Delete ${hushlogin_file}?"; then
  exit 0
fi

log::log "Removing: ${hushlogin_file}"
rm -- "${hushlogin_file}"
log::log "Removed: ${hushlogin_file}"
