#!/usr/bin/env bash

# @description Install the PackageKit command-not-found config file on Fedora when the package is installed.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! os::is_fedora; then
  exit 0
fi
if ! rpm --quiet --query 'PackageKit-command-not-found'; then
  log::log 'PackageKit-command-not-found is not installed'
  exit 0
fi

readonly src_file="${HOME}/.etc/fedora-command-not-found.conf"
readonly dest_file='/etc/PackageKit/CommandNotFound.conf'
files::root_copy "${src_file}" "${dest_file}"
