#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! executable_exists 'lxc'; then
  exit 0
fi

sudo lxc profile set default 'security.secureboot=false'
