#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../../lib/functions.bash"
check_no_args "$@"

if executable_exists 'CrashPlanDesktop'; then
  enable_system_service_unit 'crashplan-pro.service'
fi
