#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/functions.bash"
check_no_args "$@"

LC_COLLATE='C'
for script in "${SCRIPTS_DIR}/setup/"**/*; do
  # don't attempt to execute any READMEs or scripts that intentionally have their executability turned off
  if [[ -x "${script}" ]]; then
    log "Running: ${script}"
    "$script"
    log "Ran: ${script}"
  fi
done
