#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.sh"
check_no_args "$@"

for setup_script in "${SCRIPTS_DIR}/setup/"*/*; do
  log "Running: ${setup_script}"
  "$setup_script"
  log "Ran: ${setup_script}"
done
