#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_no_args "$@"

readonly autostart_dir="${XDG_CONFIG_HOME}/autostart"
create_dir "${autostart_dir}"

readonly autostart_files=(
  '/usr/share/applications/caffeine-indicator.desktop'
)
for autostart_file in "${autostart_files[@]}"; do
  if file_exists "${autostart_file}"; then
    link_file "${autostart_file}" "${autostart_dir}"
  fi
done
