#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

readonly autostart_dir="${XDG_CONFIG_HOME}/autostart"
dirs::create "${autostart_dir}"

readonly autostart_files=(
  '/usr/share/applications/caffeine-indicator.desktop'
)
for autostart_file in "${autostart_files[@]}"; do
  if files::exists "${autostart_file}"; then
    symlinks::link_file "${autostart_file}" "${autostart_dir}"
  fi
done
