#!/usr/bin/env bash

# @description Symlink selected system autostart .desktop files into the user's XDG autostart directory.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

readonly autostart_dir="${XDG_CONFIG_HOME}/autostart"
dirs::create "${autostart_dir}"

readonly autostart_files=(
  '/usr/share/applications/caffeine-indicator.desktop'
)
for autostart_file in "${autostart_files[@]}"; do
  if files::exists "${autostart_file}"; then
    symlinks::link_file "${autostart_file}" "${autostart_dir}"
  fi
done
