#!/usr/bin/env bash

# @description Configure ClamAV to log to syslog by setting LogSyslog true in /etc/clamav/clamd.conf.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

readonly clamd_conf_file='/etc/clamav/clamd.conf'

if ! files::exists "${clamd_conf_file}"; then
  exit 0
fi

log::log 'Setting ClamAV to log to syslog'
if grep::file_contains_word "${clamd_conf_file}" 'LogSyslog'; then
  sudo sed --in-place 's/^LogSyslog .*/LogSyslog true/' "${clamd_conf_file}"
else
  sudo tee --append "${clamd_conf_file}" <<< 'LogSyslog true'
fi
log::log 'Set ClamAV to log to syslog'
