#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

readonly clamd_conf_file='/etc/clamav/clamd.conf'

if ! file_exists "${clamd_conf_file}"; then
  exit 0
fi

log "Setting ClamAV to log to syslog"
if file_contains_word "${clamd_conf_file}" 'LogSyslog'; then
  sudo sed --in-place 's/.*LogSyslog .*/LogSyslog true/' "${clamd_conf_file}"
else
  sudo tee --append "${clamd_conf_file}" <<< 'LogSyslog true'
fi
log "Set ClamAV to log to syslog"
