#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! dirs::exists "${HOME}/.nix-profile/share/fonts"; then
  exit 0
fi
if symlinks::exists "${HOME}/.local/share/fonts/nix"; then
  exit 0
fi
if ! prompt::yn 'Link Nix fonts and update font cache?'; then
  exit 0
fi

log::log 'Updating font cache to include nixpkgs fonts'
dirs::create "${HOME}/.local/share/fonts"
symlinks::link_dir "${HOME}/.nix-profile/share/fonts" "${HOME}/.local/share/fonts/nix"
fc-cache --force
log::log 'Updated font cache to include nixpkgs fonts'
