#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

if ! dir_exists "${HOME}/.nix-profile/share/fonts"; then
  exit 0
fi
if [[ -L "${HOME}/.local/share/fonts/nix" ]]; then
  exit 0
fi
if ! prompt_yn 'Link Nix fonts and update font cache?'; then
  exit 0
fi

log 'Updating font cache to include nixpkgs fonts'
create_dir "${HOME}/.local/share/fonts"
link_file "${HOME}/.nix-profile/share/fonts" "${HOME}/.local/share/fonts/nix"
fc-cache --force
log 'Updated font cache to include nixpkgs fonts'
