#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_not_root
check_no_args "$@"

readonly src_file="${HOME}/.etc/sshd.conf"
readonly dest_file='/etc/ssh/sshd_config.d/sshd.conf'
copy_system_file "${src_file}" "${dest_file}"

restart_system_service_if_enabled 'sshd.service'
