#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if [[ ! -d '/etc/ssh/sshd_config.d' ]]; then
  die '/etc/ssh/sshd_config.d does not exist'
fi

readonly src_file="${HOME}/.etc/sshd.conf"
readonly dest_file='/etc/ssh/sshd_config.d/sshd.conf'
copy_system_file "${src_file}" "${dest_file}"

restart_system_service_if_enabled 'sshd.service'
