#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

readonly service_desc='SSH daemon'
readonly service_unit='sshd.service'

enable_system_service "${service_desc}" "${service_unit}"
