#!/usr/bin/env bash

# @description Set the Tailscale netfilter mode to nodivert when the tailscale binary is installed.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

if ! commands::executable_exists 'tailscale'; then
  exit 0
fi

sudo tailscale set --netfilter-mode='nodivert'
