#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::check_no_args "$@"

if ! commands::executable_exists 'tailscale'; then
  exit 0
fi

sudo tailscale set --netfilter-mode='nodivert'
