#!/usr/bin/env bash

# @description Set the Tailscale operator to the current user when the tailscale binary is installed.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
system::require_bash_version 4 0
args::check_no_args "$@"

if ! commands::executable_exists 'tailscale'; then
  exit 0
fi

sudo tailscale set --operator "${USER}"
