#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
require_bash_version 4 0
check_no_args "$@"

if ! executable_exists 'tailscale'; then
  exit 0
fi

sudo tailscale set --operator "${USER}"
