#!/usr/bin/env bash

# @description Interactively bring Tailscale up if not connected, and advertise this host as an exit node on servers/desktops.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! commands::executable_exists 'tailscale'; then
  exit 0
fi

if ! tailscale status > '/dev/null' && prompt::yn 'Connect to Tailscale network?'; then
  sudo tailscale up
  log::log "Tailscale IP: $(tailscale ip -4)"
fi

if hosts::is_server || hosts::is_desktop; then
  sudo tailscale set --advertise-exit-node
fi
