#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

readonly config_file='/etc/default/tailscaled'
readonly flag='--netfilter-mode=nodivert'

if ! file_exists "${config_file}"; then
  exit 0
fi

if grep --extended-regexp '^\s*FLAGS\s*=' "${config_file}" | contains_word "${flag}"; then
  exit 0
fi

if ! file_contains_word "${config_file}" 'FLAGS='; then
  die "${config_file} does not contain 'FLAGS='"
fi

log "Adding '${flag}' to FLAGS"
sudo sed --in-place --regexp-extended "s|^(\s*FLAGS\s*=\"?)([^\"]*)(\"?\s*)$|\1\2 ${flag}\3|" "${config_file}"
log "Added '${flag}' to FLAGS"

restart_system_service_if_enabled 'tailscaled.service'
