#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if executable_exists 'tldr'; then
  enable_user_service_unit 'tldr-update.timer'
fi
