#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

readonly service_desc='tldr page cache update'
readonly service_unit='tldr-update.timer'
readonly required_executable='tldr'
readonly system_or_user='user'

enable_service "${service_desc}" "${service_unit}" "${required_executable}" "${system_or_user}"
