#!/usr/bin/env bash

# @description Interactively add the current user to a curated list of system groups that exist on the host.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # .functions.bash is sourced via SCRIPTS_DIR, not a relative path
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

user_groups="$(groups "${USER}")"
readonly user_groups

all_groups="$(getent group | cut --delimiter=':' --fields=1)"
readonly all_groups

readonly groups=(
  'adm'
  'admin'
  'docker'
  'ftp'
  'gamemode'
  'games'
  'http'
  'kvm'
  'input'
  'libvirt'
  'log'
  'networkmanager'
  'sudo'
  'sys'
  'wheel'
)

for group in "${groups[@]}"; do
  if ! grep::contains_word "${group}" <<< "${all_groups}"; then
    continue
  fi
  if grep::contains_word "${group}" <<< "${user_groups}"; then
    continue
  fi
  if ! prompt::yn "Add ${USER} to group: ${group}?"; then
    continue
  fi
  log::log "Adding user to group: ${group}"
  sudo usermod --append --groups "${group}" "${USER}"
  log::log "Added user to group: ${group}"
done
