#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

readonly old_history_file="${HOME}/.lesshst"
readonly new_history_file="${LESSHISTFILE}"

if [[ ! -f "${old_history_file}" ]]; then
  exit 0
fi

move_user_file "${old_history_file}" "${new_history_file}"
