#!/usr/bin/env bash

set -euo pipefail

source "${SCRIPTS_DIR}/lib/functions.bash"
check_no_args "$@"

readonly old_history_file="${HOME}/.lesshst"
readonly new_history_file="${LESSHISTFILE}"

move_file "${old_history_file}" "${new_history_file}"
