#!/usr/bin/env bash

# @description Move the legacy ~/.lesshst history file to the XDG location specified by $LESSHISTFILE.
# @noargs

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/.functions.bash"
log::enable_err_trap
args::handle_help_flag "$@"
args::check_no_args "$@"

if strings::is_empty "${LESSHISTFILE:-}"; then
  exit 0
fi

readonly old_history_file="${HOME}/.lesshst"
readonly new_history_file="${LESSHISTFILE}"

if ! files::exists "${old_history_file}"; then
  exit 0
fi

files::move "${old_history_file}" "${new_history_file}"
