#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_no_args "$@"

readonly old_history_file="${HOME}/.lesshst"
readonly new_history_file="${LESSHISTFILE}"

if ! file_exists "${old_history_file}"; then
  exit 0
fi

move_file "${old_history_file}" "${new_history_file}"
