#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
enable_err_trap
check_no_args "$@"

if [[ -z "${LESSHISTFILE:-}" ]]; then
  exit 0
fi

readonly old_history_file="${HOME}/.lesshst"
readonly new_history_file="${LESSHISTFILE}"

if ! file_exists "${old_history_file}"; then
  exit 0
fi

move_file "${old_history_file}" "${new_history_file}"
