#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
check_not_root
check_no_args "$@"

if executable_exists 'gnome-session'; then
  enable_user_service_unit 'gnome-remote-desktop.service'
fi
