#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

if executable_exists 'fail2ban-client'; then
  enable_system_service_unit 'fail2ban.service'
fi
