#!/usr/bin/env bash

set -euo pipefail

source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
check_no_args "$@"

if ! executable_exists 'fail2ban-server'; then
  log 'fail2ban-server executable not found'
  exit 0
fi

readonly target_file="${HOME}/.etc/fail2ban-jail.local"
readonly link_file='/etc/fail2ban/jail.local'
link_system_file "${target_file}" "${link_file}"
