#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

readonly xsession_errors_file="${HOME}/.xsession-errors"

if ! files::exists "${xsession_errors_file}"; then
  exit 0
fi
if ! prompt::yn "Delete ${xsession_errors_file}?"; then
  exit 0
fi

log::log "Removing: ${xsession_errors_file}"
rm -- "${xsession_errors_file}"
log::log "Removed: ${xsession_errors_file}"
