#!/usr/bin/env bash

# @description Redirect /etc/X11/Xsession ERRFILE to $XDG_CACHE_HOME/X11/xsession-errors via sed-in-place.
# @noargs
# @exitcode 1 /etc/X11/Xsession exists but contains no ERRFILE= line

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # source path not known statically
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

readonly xsession_file='/etc/X11/Xsession'

if ! files::exists "${xsession_file}"; then
  exit 0
fi

# shellcheck disable=SC2016 # literal '$XDG_CACHE_HOME' is intentional - written to file as-is
if grep::file_contains_exactly "${xsession_file}" 'ERRFILE=$XDG_CACHE_HOME/X11/xsession-errors'; then
  exit 0
fi

if ! grep::file_contains_word "${xsession_file}" 'ERRFILE='; then
  log::die "${xsession_file} does not contain 'ERRFILE='"
fi

log::log 'Setting X11 ERRFILE'
sudo sed --in-place 's|^ERRFILE=.*$|ERRFILE=$XDG_CACHE_HOME/X11/xsession-errors|' "${xsession_file}"
log::log 'Set X11 ERRFILE'
