#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

#shellcheck disable=SC1091
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

if ! hosts::is_server; then
  exit 0
fi

if ! commands::executable_exists 'grub-mkconfig' && ! commands::executable_exists 'grub2-mkconfig'; then
  exit 0
fi

# These pairing of commands and GRUB output config file may not always be
# correct, but seems to be consistent with the distros I've looked at recently.
if commands::executable_exists 'grub-mkconfig'; then
  readonly grub_mkconfig_cmd='grub-mkconfig'
  readonly grub_config_file='/boot/grub/grub.cfg'
else
  readonly grub_mkconfig_cmd='grub2-mkconfig'
  readonly grub_config_file='/boot/grub2/grub.cfg'
fi
if ! files::exists "${grub_config_file}"; then
  log::die "Could not find GRUB config file at: ${grub_config_file}"
fi

readonly grub_default_file='/etc/default/grub'
if ! files::exists "${grub_default_file}"; then
  log::die "Unable to find file: ${grub_default_file}"
fi

readonly kernel_options_to_remove=(
  'rhgb'
  'quiet'
  'splash'
)

contains_options_to_remove='n'
while read -r line; do
  if grep::contains_perl_regex '^\s*(GRUB_CMDLINE_LINUX_DEFAULT|GRUB_CMDLINE_LINUX)\s*=' <<< "${line}"; then
    options="$(cut --delimiter='"' --fields=2 <<< "${line}")" || exit 1
    for kernel_option in "${kernel_options_to_remove[@]}"; do
      if printf '%s\n' "${options}" | grep::contains_word "${kernel_option}"; then
        contains_options_to_remove='y'
        break
      fi
    done
    if [[ "${contains_options_to_remove}" == 'y' ]]; then
      break
    fi
  fi
done < "${grub_default_file}"

if [[ "${contains_options_to_remove}" == 'n' ]]; then
  exit 0
fi
readonly kernel_options_to_remove_string="${kernel_options_to_remove[*]}"
if ! prompt::yn "Remove GRUB kernel options: ${kernel_options_to_remove_string// /, }"; then
  exit 0
fi

sudo cp "${grub_default_file}" "${grub_default_file}.orig"
sudo truncate --size=0 "${grub_default_file}"
while read -r line; do
  line_to_write="${line}"
  if grep::contains_perl_regex '^\s*(GRUB_CMDLINE_LINUX)|(GRUB_CMDLINE_LINUX_DEFAULT)\s*=' <<< "${line}"; then
    for kernel_option in "${kernel_options_to_remove[@]}"; do
      #shellcheck disable=SC2001
      line_to_write="$(sed "s/${kernel_option}//g" <<< "${line_to_write}")" || exit 1
    done
    line_to_write="$(sed 's/\s*"\s*/"/g ; s/\s\+/ /g' <<< "${line_to_write}")" || exit 1
  fi
  files::root_append_to "${grub_default_file}" "${line_to_write}"
done < "${grub_default_file}.orig"

sudo "${grub_mkconfig_cmd}" --output="${grub_config_file}"
